const PROMPT_BANK: string[] = [
  // --- Classic "worst / terrible" ---
  "The worst thing to say on a first date",
  "A terrible name for a pet goldfish",
  "The worst superpower to discover on your wedding day",
  "A bad reason to call 911",
  "The worst ice cream flavor that somehow got approved",
  "A terrible motto for a dating app",
  "Something that would make a hilariously bad password",
  "The worst thing to list under 'Special Skills' on a resume",
  "A rejected name for a children's TV show",
  "The worst thing to whisper to the person next to you at a funeral",
  "The worst advice to give a teenager on their first day of high school",
  "Something that would absolutely ruin a wedding reception",
  "The worst thing to find floating in your soup at a five-star restaurant",
  "A terrible excuse for being three hours late to your own birthday party",
  "The worst pickup line to use at a funeral",
  "The worst gift to give your boss at the company holiday party",
  "Something you should never do in an elevator full of strangers",
  "The worst thing to write inside a sympathy card",
  "A sport that should never, ever be in the Olympics",
  "The worst thing to say during a job interview when they ask 'Any questions?'",
  "A terrible invention that somehow got funded on Kickstarter",
  "The worst life hack of all time",
  "A self-help book title that would make everything worse",
  "The worst thing to automate with AI",
  "Something you should never put on a billboard in Times Square",
  "The worst thing to bring to show-and-tell in kindergarten",
  "A terrible name for a yoga pose",
  "The worst thing to find in your pocket at airport security",
  "A bad reason to break up with someone over text",
  "The worst thing to accidentally say on a hot mic at a press conference",
  "The most suspicious thing to Google right before a dinner party",
  "A terrible fortune cookie message to get on your birthday",
  "The worst thing to say out loud while getting a face tattoo",
  "A perfume name that would never sell",
  "The worst text to accidentally send to your entire company",
  "A reality TV show concept that would get cancelled after one episode",
  "The worst thing to yell in a quiet library",
  "A terrible name for a band that only plays at retirement homes",
  "The worst thing to say when meeting your partner's parents for the first time",

  // --- Question / scenario format ---
  "What really caused the dinosaurs to go extinct",
  "What your dog is actually thinking when it stares at you from across the room",
  "What aliens would put in their Yelp review of Earth",
  "What cats discuss at their secret 3 AM meetings",
  "What fish gossip about after the aquarium closes",
  "What your houseplants judge you hardest for",
  "What mannequins do the second the mall closes",
  "What pigeons are actually plotting in the park",
  "What your smart fridge tells the other appliances about you",
  "What really happens in the employee break room after midnight",
  "What sloths are genuinely thinking about all day",
  "What really happens to all your missing socks",
  "What the Easter Bunny does the other 364 days of the year",
  "What really goes on in the teachers' lounge",
  "What bugs say about humans in their bug language",
  "What your Roomba has seen that it wishes it could forget",
  "What really happens when you close the fridge door and the light turns off",
  "What vending machines think about the people who kick them",

  // --- Specific / detailed prompts ---
  "A sure sign your new roommate is actually a ghost",
  "The worst voicemail to accidentally leave on your ex's phone",
  "The one thing you never want your smart home to start doing on its own",
  "A surprising side effect listed on a prescription bottle that nobody reads",
  "The secret ingredient grandma will take to her grave",
  "The real reason traffic was backed up for three miles",
  "An unexpected item on a wizard's LinkedIn profile",
  "The worst thing your GPS could say while driving through the desert at night",
  "A strange thing for your dog to suddenly say in perfect English",
  "The rejected slogan that got someone fired from the marketing team",
  "The worst notification to get from your bank at 3 AM",
  "A line that was cut from a children's movie for being too dark",
  "The single worst sentence to hear from your landlord",
  "An unusual thing to find growing in your college dorm fridge",
  "The worst thing to accidentally project on screen during a work presentation",
  "A product that would instantly bomb on Shark Tank",
  "The worst thing a birthday clown could whisper to you",
  "The most concerning thing to overhear from a restaurant kitchen",
  "Something you'd find in the terms of service if you actually read them",
  "The real reason your Uber driver has a 2.3-star rating",
  "The worst possible answer to 'So, what do you do for a living?'",
  "The least reassuring thing a pilot could say before takeoff",
  "The worst thing to put in the company suggestion box on your first day",
  "A terrible way to announce you're quitting your job",
  "The worst thing to hear from the person cutting your hair halfway through",
  "The most alarming item on a restaurant's health inspection report",
  "The worst thing to say while being introduced to the Queen",
  "The most suspicious thing to be Googling at a public library",
  "A terrible way to start a best man speech",
  "The worst thing to discover about your Airbnb after midnight",
  "Something you definitely don't want to find in a hotel lost and found",
  "The worst sound to hear coming from the basement at 3 AM",
  "The worst thing to realize mid-skydive",
  "The most unhinged out-of-office email auto-reply",
  "A terrible theme for a gender reveal party that somehow makes the news",
  "The worst thing to say to someone who just showed you their newborn baby",
  "You discover your Ancestry DNA results and the weirdest thing they reveal",
  "A strange law that somehow exists in a small town",
  "The worst thing to find behind your bathroom mirror when you move in",
  "The worst response to 'I love you'",
  "A terrible warning label that would make you buy the product faster",

  // --- Madlib fill-in-the-blank ---
  "The absolute worst thing to find at the bottom of your ______",
  "Never bring ______ to Thanksgiving dinner",
  "I'm sorry officer, I had no idea it was illegal to keep ______ in my trunk",
  "The Real Housewives of ______",
  "Nobody wants a scented candle that smells like ______",
  "Worst excuse for missing work: 'I had to take my ______ to the vet'",
  "I survived the zombie apocalypse with nothing but ______ and sheer willpower",
  "It's not a real party until someone brings out the ______",
  "Instead of a mint, the world's worst hotel leaves ______ on your pillow",
  "The real secret to living past 100 is a daily glass of ______",
  "You should never, ever put ______ in a microwave",
  "The worst thing to realize you forgot right as you board a ______",
  "The worst part about living forever: ______",
  "A sure sign you've become your parents: ______",
  "The worst possible place to propose: ______",
  "The real reason we don't have flying cars: ______",
  "My spirit animal is ______ and I'm not proud of it",
  "If I were a ghost, the first thing I'd haunt: ______",
  "______ is my guilty pleasure and I will never apologize",
  "In a zombie apocalypse, my weapon of choice: ______",
  "______ would make an excellent roller coaster name",
  "If I could time travel, the first thing I'd do: ______",
  "______: sounds fun until you're three drinks in",
  "The worst way to break up with someone: ______",
  "My backup career if everything falls apart: ______",
  "______ is what I scream when I stub my toe at 2 AM",
  "The worst tattoo to get on your forehead: ______",
  "If I ran for president, my first executive order: ______",
  "Terrible band name, but excellent ______",
  "______ is the real reason I have trust issues",
  "I'm not a doctor, but I'd prescribe ______ for that",
  "New from IKEA: the ______ — some assembly required",
  "Breaking news: Florida Man arrested for ______",
  "I'd sell my soul for ______, no questions asked",
  "The last text you ever want to receive: '______'",
  "Worst inspirational poster: a sunset with the caption '______'",
  "If my life had a Yelp review, it would say: ______",
  "______ should be illegal but somehow isn't",
  "My autobiography would be titled '______'",
  "The one thing keeping me alive is ______",
  "Dear diary, today I learned the hard way that ______",
  "They say money can't buy happiness, but it can buy ______",
  "My therapist says I need to stop ______",
  "The last thing you want printed on your tombstone: ______",
  "The worst thing to find inside a birthday cake: ______",
  "The worst thing a parrot could learn to say: '______'",
  "The real reason I got banned from ______",
  "The worst way to start a TED Talk: '______'",
  "My last words will probably be: '______'",
  "Nobody warned me that adulthood was mostly ______",
  "The worst thing a fortune teller could predict: ______",
  "The real reason the chicken crossed the road: ______",
  "The worst possible Jeopardy! category: ______",
  "If aliens intercepted one thing from Earth, I hope it's not ______",
  "The world record nobody wants to hold: most ______",
  "The worst thing to hear after saying 'I do': '______'",
  "Google's top autocomplete for my name: ______",
  "The real reason your package took three weeks: ______",
  "The rejected name for a NASA mission: ______",
  "Autopsy report, cause of death: ______",
  "My criminal record would just say: ______",
  "The only thing worse than Mondays: ______",
  "The worst thing to be known for in your hometown: ______",
  "The worst name for a hurricane: ______",
  "The worst pickup line of all time: '______'",
  "The worst thing to accidentally call your teacher: ______",
  "The unspoken rule of ______ that everyone knows",
  "The worst thing to hear on a plane intercom: '______'",
  "The rejected Olympic mascot was ______",

  // --- History / real-life madlibs ---
  "The Titanic actually sank because of ______",
  "What Neil Armstrong actually said when he stepped on the moon: '______'",
  "The real reason Napoleon always had his hand in his jacket: ______",
  "The Egyptian pyramids were actually built to ______",
  "The real message behind the Mona Lisa's smile: ______",
  "What was really in Al Capone's vault: ______",
  "The real reason Area 51 is so heavily guarded: ______",
  "The Bermuda Triangle is actually caused by ______",
  "The real reason the Berlin Wall came down: ______",
  "What Cleopatra was actually famous for: ______",
  "The secret clause in the Declaration of Independence: ______",
  "What the builders of Stonehenge were actually trying to do: ______",

  // --- Pop culture / modern ---
  "The worst sequel nobody asked for: ______ 2",
  "Worst Taylor Swift breakup song title",
  "______ would make a terrible Jedi",
  "The celebrity most likely to accidentally start a cult",
  "The real reason Darth Vader turned to the dark side",
  "A TikTok trend that would end civilization",
  "The worst person to be stuck in an escape room with",
  "If AI took over, the first thing it would cancel: ______",
  "The worst character to cosplay at a job interview",
  "______ is just Batman with extra steps",
  "The worst contestant on The Bachelor would be ______",
  "A Disney movie that should never get a live-action remake",

  // --- Absurd / creative ---
  "A new crayon color that Crayola would never approve",
  "The worst thing to name your WiFi network in an apartment building",
  "A terrible name for a cruise ship",
  "The most passive-aggressive thing to name your sourdough starter",
  "The worst name for a children's hospital clown",
  "A terrible name for a brand of discount parachutes",
  "The worst motivational speech to give right before a skydive",
  "The worst company to sponsor a children's sports team",
  "A terrible tagline for a haunted house that's trying to be family-friendly",
  "The worst name for a therapy dog",
  "The most suspicious item to buy in bulk at 2 AM",
  "The worst thing to embroider on a throw pillow",
  "A terrible name for a brand of baby food",
  "The worst motivational quote to hang in a classroom",
  "The most concerning thing to find in a suggestion box",
  "The worst question to ask at a town hall meeting",
  "A terrible thing to yell while being wheeled into surgery",
  "The worst thing to overhear through thin apartment walls",
  "A suspicious thing to know way too much about on a first date",
  "The worst flavor of lip balm",
  "A terrible name for a support group",
  "The worst thing to write on a 'Get Well Soon' balloon",
  "A bad slogan for a skydiving company",
  "The most awkward thing to put in your dating profile bio",
  "The worst name for a school mascot",
  "A terrible thing to monogram on a bathrobe gift",
  "A bad name for a search-and-rescue helicopter",
  "The worst name for a couples' retreat",
  "A terrible name for a children's book about sharing",
  "The worst thing to hear from a talking toilet",
  "A bad name for an emergency exit door",
  "The worst country to accidentally declare war on",
  "A terrible name for a neighborhood watch group",
  "The worst possible name for a deodorant",
  "A bad slogan for a dentist's office",
  "The worst thing to find at the bottom of a ball pit",
  "A terrible name for a preschool",
  "The worst thing to put in a piñata besides candy",
  "A bad name for a life insurance company",
  "The worst thing to shout from a rooftop",

  // --- Corporate hell / adulting ---
  "The most unhinged LinkedIn post you've ever seen",
  "The worst icebreaker at a mandatory corporate team-building retreat",
  "The worst 'fun fact about yourself' to share on your first day of work",
  "The most unsettling thing to say during a performance review",
  "An HR complaint that would immediately get you a second HR complaint",
  "The worst thing to put in a company-wide Slack message",
  "The worst thing to bring up at an HOA meeting",
  "What your credit score says about you as a person",
  "The worst thing to discover on your itemized hospital bill",
  "A terrible thing to say to the person behind you in line at the DMV",
  "The worst thing to mutter under your breath at a PTA meeting",
  "The most passive-aggressive email sign-off",
  "The worst noise to make during a conference call you forgot to mute",
  "A terrible thing to write on a noise complaint",

  // --- Technology nightmares ---
  "The worst autocorrect to send to your mother-in-law",
  "The most alarming thing in someone's browser history",
  "The worst thing for Alexa to say unprompted at 3 AM",
  "The group chat message that ends a friendship",
  "The worst thing for your phone to autocomplete after 'Hey Mom, I just'",
  "The most cursed thing to find in someone's camera roll",
  "The worst thing your smart TV could recommend based on your viewing habits",
  "An app notification that would ruin your day",
  "The worst thing to go viral for",

  // --- Food crimes ---
  "A pizza topping that should be a felony",
  "The worst thing to bring to a church bake sale",
  "A food combination that should land you in prison",
  "The worst daily special at a food truck called 'Trust Me Bro'",
  "The most unhinged thing to order at a drive-through at 3 AM",
  "The worst cooking show hosted by someone who clearly can't cook",
  "A terrible name for a meal kit delivery service",
  "The worst thing to dip a chicken nugget in",

  // --- Childhood / fairy tales gone wrong ---
  "A terrible moral for a children's fable",
  "The worst thing to hide in an Easter egg hunt",
  "A deleted scene from your favorite fairy tale",
  "The worst bedtime story for a five-year-old",
  "The worst prize in a cereal box",
  "A terrible revision to the rules of hide-and-seek",
  "The worst field trip a school has ever taken",
  "A children's song lyric that hits different as an adult",

  // --- Confessions / uncomfortable truths (madlib) ---
  "I'm not saying it was my fault, but ______",
  "My search history proves that I'm ______",
  "I peaked in life when ______",
  "The hill I will absolutely die on: ______",
  "I'm one bad day away from ______",
  "The thing I pretend to understand but definitely don't: ______",
  "My biggest red flag: ______",
  "The lie I tell most often: ______",
  "I have never once in my life successfully ______",
  "I'm not proud of it, but I once ______",
  "The thing I'd confess on my deathbed: ______",

  // --- Deeply specific scenarios ---
  "The worst thing to say to a cop while eating a burrito during a traffic stop",
  "A terrible thing to admit during a game of Never Have I Ever",
  "The worst thing to say to customs when they ask the purpose of your visit",
  "The worst thing to whisper to the person next to you during heavy turbulence",
  "A terrible thing to be caught doing by your neighbor at 4 AM",
  "The worst thing to say when the waiter asks 'How is everything?'",
  "The worst thing to say to someone clearly crying in the office bathroom",
  "The most alarming thing to yell when the roller coaster gets stuck upside down",
  "The worst thing to be doing when the Zoom camera accidentally turns on",
  "A terrible thing to whisper to a baby at a christening",
  "The worst thing to say to the person sitting next to you on a 14-hour flight",
  "The worst thing to say when someone asks if you want to hold their baby",

  // --- Products / services that shouldn't exist ---
  "An infomercial product for a problem that nobody has",
  "The worst item to sell on a home shopping network at 3 AM",
  "A subscription service that absolutely should not exist",
  "The worst product to advertise during the Super Bowl",
  "A terrible name for a brand of children's vitamins",
  "The worst thing to sell at a school fundraiser",
  "A gym membership perk that would make everyone cancel",

  // --- Animals being unhinged ---
  "The worst thing a parrot could say in front of your in-laws",
  "What geese would say if they could talk",
  "The crime your cat would commit if it had thumbs",
  "What raccoons are actually doing with all that garbage",
  "The worst animal to show up uninvited to your wedding",
  "What seagulls are screaming about",
  "The petition your dog would start if it understood the internet",

  // --- Existential but make it funny ---
  "The worst thing to realize at 3 AM when you can't sleep",
  "A terrible thought to have during a moment of silence",
  "The worst epiphany to have in a grocery store parking lot",
  "What the light at the end of the tunnel actually is",
  "The most depressing fortune cookie message that's technically accurate",
  "God's most regrettable creation",
  "The worst thing to hear from your guardian angel",

  // --- Social situations from hell ---
  "The worst icebreaker on the first day of prison",
  "The most unhinged voicemail to leave a restaurant after a bad meal",
  "A bumper sticker that would get your car keyed",
  "The worst thing to engrave on a trophy",
  "The worst thing to caption a family photo with",
  "An alarming thing to overhear at a children's playground",
  "The worst thing to say into a walkie-talkie",
  "The worst thing to say to your Lyft driver right as you get in the car",
  "The worst way to end a hug",
  "The worst thing to be the last person caught doing on a security camera",
  "The worst thing to yell across a crowded restaurant to get your friend's attention",

  // --- More madlibs ---
  "Welcome to ______, how can I help you today",
  "Scientists just discovered that ______ is actually good for you",
  "The hidden track on the worst album ever: '______'",
  "The worst thing to name a boat: ______",
  "My dating profile says I'm into ______ and honestly that's accurate",
  "The thing no one tells you about turning 30: ______",
  "The worst way to describe your job to a child: ______",
  "The most ominous thing a child has ever said: '______'",
  "The first rule of ______ is we don't talk about it",
  "The worst thing to hear from your dentist mid-procedure: '______'",
  "The rejected Monopoly piece was ______",
  "The thing I'd grab first in a house fire: ______",
  "My Uber driver rating dropped because ______",
  "The worst thing to be allergic to: ______",
  "Leaked government document reveals ______",
  "The worst thing to name a sword: ______",

  // --- Foreign language easter eggs ---
  "你绝对不应该在第一次约会时说的话",          // The thing you should never say on a first date (Chinese)
  "Lo peor que puedes gritar en un elevador lleno de gente", // The worst thing to yell in a crowded elevator (Spanish)
  "おばあちゃんの秘密の材料は実は______",        // Grandma's secret ingredient is actually ______ (Japanese)
  "La pire excuse pour arriver en retard à son propre mariage", // The worst excuse for being late to your own wedding (French)
  "Das Schlimmste, was man bei einer Beerdigung laut sagen könnte", // The worst thing to say out loud at a funeral (German)
  "지구에 대한 외계인의 Yelp 리뷰",              // An alien's Yelp review of Earth (Korean)
  "La peor cosa da scrivere su una torta di compleanno", // The worst thing to write on a birthday cake (Italian)
  "Самое худшее, что можно шепнуть незнакомцу в автобусе", // The worst thing to whisper to a stranger on a bus (Russian)
  "أسوأ شيء تصرخ به في مصعد مزدحم",                    // The worst thing to shout in a crowded elevator (Arabic)
  "สิ่งที่ไม่ควรพูดกับแม่ยายในมื้อแรก",                        // What you shouldn't say to your mother-in-law at the first meal (Thai)
  "Điều tệ nhất để viết lên bánh cưới",                  // The worst thing to write on a wedding cake (Vietnamese)
  "O pior conselho para dar a alguém que está prestes a saltar de paraquedas", // The worst advice to give someone about to skydive (Portuguese)
  "Het ergste om per ongeluk te zeggen tijdens een sollicitatiegesprek", // The worst thing to accidentally say during a job interview (Dutch)
  "Det värsta att viska till personen bredvid dig på en begravning", // The worst thing to whisper to the person next to you at a funeral (Swedish)
  "Najgorsze, co można powiedzieć przy pierwszym spotkaniu z teściową", // The worst thing to say when meeting your mother-in-law (Polish)
  "Cel mai prost lucru pe care să-l strigi într-o bibliotecă", // The worst thing to yell in a library (Romanian)
  "Az orvos legrosszabb mondata a műtét közepén: '______'", // The worst thing for a doctor to say mid-surgery: '______' (Hungarian)
  "Ang pinakamasamang bagay na isulat sa isang sympathy card", // The worst thing to write in a sympathy card (Filipino/Tagalog)
  "पायलट ने उड़ान भरने से पहले जो सबसे बुरी बात कही: '______'", // The worst thing a pilot said before takeoff: '______' (Hindi)
  "택시 기사에게 절대 하면 안 되는 말: '______'",          // What you should never say to a taxi driver: '______' (Korean)
  "Kötü bir süper kahraman ismi: ______",                // A bad superhero name: ______ (Turkish)
  "Pahin asia, jonka voi kuulla hammaslääkäriltä: '______'", // The worst thing to hear from your dentist: '______' (Finnish)
  "Nejhorší věc, kterou říct na prvním rande",            // The worst thing to say on a first date (Czech)
  "Det verste å rope under en begravelse",               // The worst thing to shout during a funeral (Norwegian)
  "ရေခဲမုန့်အရသာ အဆိုးဆုံးအမည်: ______",               // The worst ice cream flavor name: ______ (Burmese)
  "Perkara paling teruk untuk ditulis pada kad hari jadi", // The worst thing to write on a birthday card (Malay)
  "Värsta saken att skrika på ett flygplan: '______'",   // The worst thing to shout on a plane: '______' (Swedish)
  "בדיחה שלעולם לא כדאי לספר בראיון עבודה",              // A joke you should never tell at a job interview (Hebrew)
  "Το χειρότερο πράγμα να πεις σε κηδεία: '______'",    // The worst thing to say at a funeral: '______' (Greek)
  "人生最悪のタイミングで鳴る着信音: ______",                // The worst ringtone to go off at the worst time: ______ (Japanese)
  "机场安检时口袋里最不该有的东西: ______",                  // The worst thing to have in your pocket at airport security: ______ (Chinese)

  // --- Meme culture / internet ---
  "The 'Is this a ______?' butterfly guy, but he's pointing at something truly unhinged",
  "Distracted boyfriend is looking at ______",
  "The 'this is fine' dog, but the room is on fire because of ______",
  "POV: You just ______",
  "Nobody: Absolutely nobody: Me at 3 AM: ______",
  "Me explaining to my mom why I need ______ (conspiracy board meme)",
  "The Drake 'no' panel vs the Drake 'yes' panel, but it's ______",
  "Two wolves inside you: one wants ______, the other wants ______",
  "The 'they're the same picture' meme, but it's comparing ______ and ______",
  "The scroll of truth says: '______'",
  "Mr. Incredible becoming uncanny because of ______",
  "Gru's plan, but the third panel reveals ______",
  "Skeletor's disturbing fact of the day: ______",
  "The rock eyebrow raise, but he just heard ______",
  "Trade offer: I receive ______, you receive ______",
  "Woman yelling at the cat, but they're arguing about ______",
  "The 'always has been' astronaut meme, but it's about ______",
  "Bernie Sanders is once again asking for ______",
  "The 'how it started vs how it's going' but for ______",
  "Change my mind: ______",
  "The worst thing to put on the 'corporate wants you to find the differences' meme",
  "The 'guess I'll die' guy, but it's because ______",
  "The 'surprised Pikachu' moment of the century: ______",
  "Evil ______ be like: ______",
  "The 'we have ______ at home' and at home it's ______",
  "The strongest man vs the weakest ______ fan",
  "One does not simply ______ into Mordor",
  "Bro really said '______' and thought we wouldn't notice",
  "The 'it's evolving, just backwards' moment: ______",
  "OK but why does ______ go so hard",
  "Core memory unlocked: ______",
  "The intrusive thought that won: ______",
  "Real ones remember ______",
  "Tell me you're ______ without telling me you're ______",
  "The most unhinged thing someone ever posted and then said 'anyway': ______",
  "Certified ______ moment",
  "The 'I lived bitch' energy of ______",
  "The 'understandable, have a great day' response to ______",
  "Ight imma head out, but only because ______",
  "The 'they don't know I ______' guy at the party",
];

function cryptoRandInt(max: number): number {
  const array = new Uint32Array(1);
  crypto.getRandomValues(array);
  return array[0] % max;
}

function shuffle<T>(array: T[]): T[] {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = cryptoRandInt(i + 1);
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export function getRandomPrompts(
  count: number,
  exclude: Set<string> = new Set(),
): string[] {
  const available = PROMPT_BANK.filter((p) => !exclude.has(p));
  return shuffle(available).slice(0, count);
}
