const PROMPT_BANK: string[] = [
  // ==========================================================================
  // SOCIAL LANDMINES — things to say, do, find, or discover in specific
  // situations. The bread and butter of Quiplash: high-stakes embarrassment.
  // ==========================================================================

  // Dates, relationships & family
  "The worst thing to accidentally say out loud on a first date",
  "The worst thing to say when meeting your partner's parents for the first time",
  "A bad reason to break up with someone over text",
  "The most awkward thing to put in your dating profile bio",
  "A suspicious thing to know way too much about on a first date",
  "A suspicious thing to be caught Googling by your partner",
  "A terrible thing to say while someone is showing you their family tree",
  "The worst thing to caption a family photo with",
  "The most unhinged thing someone's dating app AI wrote on their behalf",
  "The worst thing to discover about your date by Googling them at the table",

  // Work & professional
  "The worst thing to say during a job interview when they ask 'Any questions?'",
  "The worst thing to list under 'Special Skills' on a resume",
  "The worst thing to accidentally say on a hot mic at a press conference",
  "A terrible way to announce you're quitting your job",
  "A terrible way to start a best man speech",
  "The worst thing to put in the company suggestion box on your first day",
  "The worst possible answer to 'So, what do you do for a living?'",
  "The worst way to find out you've been fired",
  "The worst thing to accidentally project on screen during a work presentation",
  "The worst thing to accidentally say in a company-wide reply-all email",
  "The most passive-aggressive thing to write on a coworker's going-away card",

  // Travel & transit
  "The worst thing to find in your pocket at airport security",
  "The worst thing to say to customs when they ask the purpose of your visit",
  "The worst thing to say to the person sitting next to you on a 14-hour flight",
  "The worst thing to whisper to the person next to you during heavy turbulence",
  "The least reassuring thing a pilot could say before takeoff",
  "The worst thing to say to your Lyft driver right as you get in the car",
  "The worst thing to discover about your Airbnb after midnight",
  "Something you definitely don't want to find in a hotel lost and found",

  // Weddings, funerals & ceremonies
  "The worst thing to whisper to the person next to you at a funeral",
  "Something that would absolutely ruin a wedding reception",
  "The worst superpower to discover on your wedding day",
  "The worst gift to give your boss at the company holiday party",
  "The worst thing to write inside a sympathy card",
  "A terrible thing to whisper to a baby at a christening",
  "A terrible theme for a gender reveal party that somehow makes the news",
  "The worst thing to blurt out while being knighted with a sword",

  // Food & dining
  "The worst thing to find floating in your soup at a five-star restaurant",
  "The most concerning thing to overhear from a restaurant kitchen",
  "The worst thing to say when the waiter asks 'How is everything?'",
  "The most alarming item on a restaurant's health inspection report",
  "The most unhinged voicemail to leave a restaurant after a bad meal",
  "The worst thing to bring to a potluck and act like it's normal",

  // Medical & emergency
  "A reason to call 911 that would make the dispatcher hang up on you",
  "A terrible thing to yell while being wheeled into surgery",
  "The worst thing to discover your surgeon Googling right before your operation",
  "The worst thing to realize mid-skydive",
  "The worst side effect listed on a medication commercial that nobody questions",
  "A terrible thing to overhear your therapist say about you to another therapist",

  // Encounters with strangers & acquaintances
  "The worst thing to say to a cop while eating a burrito during a traffic stop",
  "The worst first thing to say into a walkie-talkie on day one as a mall security guard",
  "The worst thing to shout from a rooftop at 3 AM that technically isn't a crime",
  "The worst thing to yell across a crowded restaurant to get your friend's attention",
  "Something you should never do in an elevator full of strangers",
  "Something you should never put on a billboard in Times Square",
  "A bumper sticker that would get your car keyed",
  "The worst thing to be the last person caught doing on a security camera",

  // Everyday & miscellaneous social
  "A terrible excuse for being three hours late to your own birthday party",
  "The worst thing to say to someone who just showed you their newborn baby",
  "The worst thing to say out loud while getting a face tattoo",
  "The worst thing to bring to show-and-tell in kindergarten",
  "The most suspicious thing to Google right before a dinner party",
  "The worst thing to overhear through thin apartment walls",
  "An alarming thing to overhear at a children's playground",
  "A terrible thing to be caught doing by your neighbor at 4 AM",
  "A terrible thing to be caught practicing in the mirror",
  "An inappropriate time to do a victory dance",
  "The worst thing to be doing when the rapture happens",
  "The worst thing to be doing when the Zoom camera accidentally turns on",
  "A terrible thing to admit during a game of Never Have I Ever",
  "The worst thing to say to someone clearly crying in the office bathroom",
  "The most alarming thing to yell when the roller coaster gets stuck upside down",
  "A terrible thing to say to comfort someone stuck in an elevator",
  "The worst thing to write on a 'Get Well Soon' balloon",
  "Something you'd be surprised to see a grandma pull out of her purse",
  "Something you should never do while holding a baby",
  "The 'before and after' transformation on social media that went horribly wrong",
  "The worst thing to discover your kid drew in art class and titled 'My Family'",
  "A terrible thing to be doing when the earthquake drill turns out to be real",
  "The worst thing to say after someone finishes singing happy birthday to you",
  "The worst thing to say when someone hands you their phone to show baby pictures",
  "A terrible thing to yell while parallel parking on a crowded street",
  "The least helpful thing to say when the guest of honor walks in early to their surprise party",
  "The worst thing to whisper right before a group photo at a wedding",
  "A terrible thing to say while helping someone move a couch up stairs",
  "I couldn't attend the wedding because my plus-one is ______",
  "A terrifying thing to hear a mall Santa whisper to an elf",
  "The worst thing to whisper while getting a massage is ______",
  "The worst thing to bring to a medieval potluck",
  "The best part about getting trapped in a revolving door with your CEO",
  "The worst thing to discover at the bottom of a Chuck E. Cheese ball pit",
  "The worst thing to hear the person in the bathroom stall next to you say",
  "A bad reason to press the emergency stop button on an escalator",
  "The worst thing to find stuffed inside a Thanksgiving turkey",
  "The worst way to break the ice on a crowded submarine",
  "The worst thing to accidentally broadcast on the stadium kiss cam",
  "The most unhinged thing to knit into a sweater for your grandson",
  "The worst question to ask during a haunted walking tour",
  "The worst excuse for accidentally backing your car into a police cruiser",
  "The worst thing to overhear your Uber driver whispering to themselves",
  "The worst thing to realize while getting a spray tan",
  "The worst thing to yell when the club DJ drops the beat",
  "A terrible thing to put in a piñata at a retirement home",
  "The worst thing to scream while jumping out of a giant birthday cake",
  "The worst thing to be handed while running a marathon",
  "The worst thing to do while making aggressive eye contact",
  "The most concerning thing to see a mall security guard doing",
  "The most concerning poster to see in a dentist's waiting room",
  "The most threatening aura to bring to a neighborhood bake sale",
  "The worst thing to mutter while slowly backing out of a room",
  "The worst way to prove you're not a robot during a job interview",
  "A terrible thing to announce over the intercom at a grocery store",
  "The worst thing to say to the person spotting you at the gym",
  "The most alarming thing to do with a shopping cart in a parking lot",
  "The worst thing to accidentally leave in the self-checkout bagging area",
  "The worst thing to confidently explain to a stranger at a bus stop",
  "A terrible thing to say to someone whose name you clearly forgot",
  "The worst thing to do during a moment of silence at a sporting event",
  "The most unhinged thing to do in a hotel elevator when the doors open",
  "The worst thing to say to someone who just showed you their tattoo",
  "The worst thing to accidentally send to your landlord instead of your best friend",
  "A terrible thing to whisper to the person cutting your hair",
  "The worst way to introduce yourself at a neighborhood block party",
  "A terrible thing to say when the barista asks your name for the cup",

  // Oddly specific & inherently funny
  "Something you could say at both a funeral and a gender reveal party",
  "A phrase that's perfectly fine at a barbecue but devastating at a custody hearing",
  "A sentence that's completely normal at a zoo but terrifying at a hospital",
  "Something that sounds supportive but is actually the most devastating insult",
  "Something you should never say while holding a chainsaw, even if you mean well",
  "Something that is fine to say once but psychotic to say twice in a row",
  "The thing a man says right before making the worst decision of his life",
  "The worst thing to overhear from a clown who just got off the phone crying",
  "The most threatening thing a grandmother has ever said while holding a wooden spoon",
  "The worst thing to say with complete confidence to a group of people who did not ask",
  "A compliment that would actually make you more uncomfortable than an insult",
  "Something that's only romantic in movies but absolutely psychotic in real life",
  "The sentence that has never once in history been said calmly",
  "Something you should not Google while someone is looking over your shoulder, even though it's completely innocent",
  "The most dangerous sentence that begins with 'I watched a video about this'",
  "The one thing you could say at any Walmart and the stranger next to you would just nod",
  "Something only a person with absolutely nothing left to lose would say at a parent-teacher conference",
  "The worst thing to say to a man in full medieval armor at a Wendy's",
  "Something that's technically not illegal but should absolutely get you exiled",
  "A skill that sounds impressive until you explain how you learned it",
  "The thought every person has when they see someone running who isn't in workout clothes",
  "The most chaotic thing to do during an office fire drill",
  "The worst thing to be doing when you accidentally make eye contact with someone through a window",
  "Something you can never unhear once your dad says it",
  "The exact wrong thing to say when someone is showing you how to do something simple",
  "The worst way to find out you're not someone's best friend",
  "Something no human being has ever said enthusiastically",
  "The one thing you can do at a party that will make everyone think you're either a genius or insane",
  "The worst thing to discover about yourself from a personality quiz at a party",
  "Something that is a completely normal amount to own one of, but deeply alarming to own twelve of",
  "The thing every person does when they're home alone that they would deny under oath",
  "The unspoken rule of the all-you-can-eat buffet that everyone silently enforces",
  "The one item at IKEA that has ended the most relationships",
  "The single most dangerous aisle at Costco and why",
  "The thing every person does in a waiting room that they think nobody else notices",
  "Something everyone has rehearsed in the shower but will never actually say out loud",
  "The unconvincing lie every parent tells and every kid immediately sees through",
  "The thing you tell yourself to justify a purchase you absolutely cannot afford",
  "A power move so subtle only three people in history have ever noticed it",
  "The single bravest thing you can do at a salad bar",
  "An incredibly specific phobia that way more people have than will ever admit",

  // School & college
  "The worst thing to write in a college application essay's opening line",
  "The most alarming thing a substitute teacher has ever said on day one",
  "The worst senior yearbook quote that somehow got approved",
  "A terrible theme for prom that the student council actually voted for",
  "The worst group project partner excuse for not doing their part",
  "The most unhinged extra credit assignment a professor has ever offered",
  "The worst thing to be caught doing during a final exam",
  "The worst advice from a college orientation leader",
  "The most alarming thing written on a college dorm whiteboard",
  "The thing every college student has done at 4 AM that they'll never admit",

  // Music & concerts
  "The worst song to play at a funeral that technically fits the vibe",
  "The worst thing to request at a wedding DJ booth",
  "The worst karaoke song to dedicate to your ex who is in the audience",
  "The worst thing to yell between songs at a quiet acoustic set",
  "The worst lyric to mishear and confidently sing at full volume",

  // Holidays & seasonal
  "The worst thing to put in a Christmas card to your entire family",
  "The most passive-aggressive Valentine's Day gift",
  "A terrible Halloween costume that is technically not offensive but deeply unsettling",
  "The worst Secret Santa gift from someone who clearly doesn't like you",
  "The thing that ruined Thanksgiving before anyone even sat down",

  // ==========================================================================
  // NAMING & CREATING — name a product, band, word, slogan, etc.
  // The "come up with a name" format consistently produces the funniest answers.
  // ==========================================================================
  "Name a candle scent designed specifically for guys who peaked in high school",
  "Come up with a name for the sketchy gas station energy drink nobody should try",
  "Name a workout class that would empty the gym in seconds",
  "Come up with a name for a dating app exclusively for people with terrible judgment",
  "Name a font nobody would ever use on a resume",
  "Come up with a name for a perfume by your most unhinged ex",
  "Name a cocktail that would get you banned from the bar permanently",
  "Name a children's book by someone who clearly hates children",
  "Make up a word for the feeling you get when you wave back at someone who wasn't waving at you",
  "Come up with a catchy but deeply wrong slogan for a funeral home",
  "Name a DJ who should absolutely not be allowed near a turntable",
  "A rejected name for a children's TV show",
  "A terrible name for a band that only plays at retirement homes",
  "The worst name for a children's hospital clown",
  "A terrible name for a brand of discount parachutes",
  "A terrible name for a support group that meets in a church basement on Tuesdays",
  "A terrible name for a neighborhood watch group",
  "The worst thing to name your WiFi network in an apartment building",
  "The most passive-aggressive thing to name your sourdough starter",
  "A new crayon color that Crayola would never approve",
  "The worst ice cream flavor that somehow got approved",
  "A terrible motto for a dating app",
  "A bad slogan for a skydiving company",
  "A terrible tagline for a haunted house that's trying to be family-friendly",
  "A self-help book title that would make everything worse",
  "A terrible warning label that would make you buy the product faster",
  "A reality TV show concept that would get cancelled after one episode",
  "Name a cologne that smells exactly like poor decisions",
  "Name a therapy app for people whose therapist gave up on them",
  "Name a startup that would get funded but definitely shouldn't exist",
  "Come up with a name for a cruise ship that's definitely going to sink",
  "A rejected Girl Scout cookie flavor",
  "Name a gym that specifically targets people who will never actually go",
  "Come up with a name for Ozempic but for your personality",
  "Name a TED Talk that would get the speaker escorted offstage",
  "A terrible name for a service dog",
  "Name a new Gatorade flavor for people going through a breakup",
  "Come up with a name for a meal-kit service for people who only own one pan",
  "A terrible title for a mindfulness podcast hosted by a very angry man",
  "Name a frozen dinner for people going through a midlife crisis",
  "A rejected slogan for a luxury bunker community",
  "Name a cruise excursion nobody should book while sober",
  "A rejected name for a brand of organic baby food",
  "Name a deodorant specifically formulated for crypto bros",
  "Come up with a name for a discount plastic surgery clinic",
  "A terrible name for a brand of recycled toilet paper",
  "A rejected title for a Nicholas Sparks novel",
  "A rejected flavor of vape juice",
  "Come up with a name for a pirate-themed strip club",
  "A terrible name for a 24-hour diner in New Jersey",
  "Name a terrible brand of discount contact lenses",
  "A terrible name for a vegan butcher shop",
  "Name a terrible charity started by a tech billionaire",
  "Name a rejected theme park ride from Disneyland",
  "A terrible name for a couples therapy retreat",
  "Name a budget airline that you should absolutely not fly",
  "A rejected name for a line of senior citizen energy drinks",
  "Come up with a name for a gym that's clearly a front for something else",
  "Name the off-brand cereal mascot that haunts your nightmares",
  "A terrible name for an escape room designed by your HR department",
  "Name a podcast that has exactly one listener and it's the host's mom",
  "Come up with a name for a restaurant where every meal is a surprise and not in a good way",
  "A terrible name for a children's magician who keeps getting fired",
  "Name a wellness retreat that is definitely a cult",
  "A country song title that's too honest",
  "A terrible name for a one-hit wonder's follow-up album",
  "A rap bar so bad it ends the entire genre",
  "A terrible opening act for a children's music concert",
  "A New Year's resolution that lasts exactly 11 minutes",
  "The worst 4th of July fireworks show theme",
  "A terrible thing to write on a Valentine's Day candy heart",
  "The worst thing to carve into a pumpkin for the neighborhood to see",
  "The true crime podcast title that went too far",
  "Name a hot sauce that's clearly going through a divorce",
  "A craft beer name that would make your grandfather weep",
  "A yoga pose that sounds like it should be a felony",
  "Name a candle scent that perfectly captures 'crying in a Honda Civic at noon'",
  "A rejected Ben & Jerry's flavor that was just too honest",
  "Name a cryptocurrency that absolutely everyone saw tanking from day one",
  "A martial art specifically designed for people who just want to argue",
  "Name a spa treatment that is technically just a punishment",
  "Name the specific type of guy who always brings a guitar to a party where nobody asked",
  "Name a protein bar that tastes like giving up",
  "Name the specific breed of person who sends 'u up?' texts at 2 AM",
  "Name a podcast hosted by someone who definitely should not have a platform",
  "Name a boat that you should never, under any circumstances, name a boat",
  "A wine name that is trying way too hard",
  "Name a workout that's technically just suffering with better marketing",
  "Name a holiday that would immediately divide the country",
  "A font that radiates the energy of someone who peaked in middle school",
  "Name a fragrance inspired by the specific vibe of a hotel breakfast buffet",

  // ==========================================================================
  // HIDDEN TRUTHS & SECRET LIVES — what X really thinks, does, or is hiding.
  // Conspiracy-style absurdism and anthropomorphic humor.
  // ==========================================================================
  "What your dog is actually thinking when it stares at you from across the room",
  "What aliens would put in their Yelp review of Earth",
  "What cats discuss at their secret 3 AM meetings",
  "What your houseplants judge you hardest for",
  "What pigeons are actually plotting in the park",
  "What your smart fridge tells the other appliances about you",
  "What the Easter Bunny does the other 364 days of the year",
  "What your Roomba has seen that it wishes it could forget",
  "What raccoons are actually doing with all that garbage",
  "What seagulls are screaming about",
  "Something squirrels are definitely plotting behind your back",
  "The petition your dog would start if it understood the internet",
  "The crime your cat would commit if it had thumbs",
  "The worst animal to show up uninvited to your wedding",
  "The worst thing a parrot could say in front of your in-laws",
  "A strange thing for your dog to suddenly say in perfect English",
  "A sure sign your new roommate is actually a ghost",
  "The one thing you never want your smart home to start doing on its own",
  "The secret ingredient grandma will take to her grave",
  "The real reason traffic was backed up for three miles",
  "Something you'd find in the terms of service if you actually read them",
  "The real reason your Uber driver has a 2.3-star rating",
  "An unusual thing to find growing in your college dorm fridge",
  "The worst thing to find behind your bathroom mirror when you move in",
  "The real reason your neighbor built that fence so high",
  "A strange law that somehow exists in a small town",
  "Something that is weirdly improved by adding cheese",
  "What Siri actually thinks when you ask a dumb question at 2 AM",
  "What your therapist writes in their notes after you leave",
  "What your emotional support animal secretly judges you for",
  "The real reason your WiFi goes out every time you're about to win an argument online",
  "What your smoke detector is really trying to tell you at 2 AM",
  "What ducks are gossiping about at the park pond",
  "The real reason your package says 'out for delivery' all day",
  "What the hotel ice machine has witnessed that changed it forever",
  "What the microwave is actually doing when it hums for three minutes",
  "The real reason dogs spin around before they poop",
  "What the tooth fairy actually does with all those teeth",
  "The real reason the ice cream machine at McDonald's is always broken",
  "What historians will wrongly assume about Florida in 1000 years",
  "The real reason they don't let you touch the art in museums",
  "What the gargoyles on old cathedrals are actually looking at",
  "The secret society of grandmas is secretly controlling ______",
  "The real reason dad went to get milk and never came back",
  "The real reason the dinosaurs actually went extinct",
  "What the local raccoons call you behind your back",
  "The unwritten rule of the Waffle House at 3 AM",
  "What your grocery cart says about you as a person",
  "The real reason the elevator makes that noise between floors",
  "What the shopping cart with the wobbly wheel is trying to tell you",
  "What your thermostat setting reveals about your childhood",
  "The thing your pizza delivery driver judges you hardest for",
  "What gas station bathrooms have seen that made them give up",
  "What the last slice of pizza in the box is thinking",
  "The real reason your neighbor mows the lawn at 7 AM on a Saturday",
  "What vending machines would say if they could refuse service",
  "The unspoken agreement between you and the person you keep seeing at the same coffee shop",
  "What traffic cones are secretly protecting",
  "The most alarming thing on a rock band's hotel room rider",
  "The conspiracy theory that's too stupid to be wrong",
  "The thing the government is definitely hiding in a warehouse somewhere",
  "What the birds are actually reporting back to",
  "The real reason they stopped going to the moon",
  "Bigfoot's most embarrassing secret",
  "The most reasonable demand on an alien's list of conditions for first contact",
  "What the DMV employees discuss when absolutely no citizens are present",
  "The real reason you've never seen a baby pigeon",
  "The thing your barber is specifically trained to never say out loud",
  "The single thought going through a cat's head right before it knocks your water glass off the table",
  "What geese are obviously training for and why we should all be worried",
  "What a seagull would tell its therapist about the parking lot incident",
  "What the car wash brushes whisper to each other between vehicles",
  "The thing a lobster thinks about while sitting in the restaurant tank",
  "What a fish genuinely believes rain is",
  "The real reason aliens keep visiting Earth but refuse to make official contact",
  "The thing the office printer has been plotting this entire time",
  "What the other Monopoly pieces say about the thimble behind its back",
  "What the office plant has overheard that would absolutely destroy the company",
  "What the Statue of Liberty is actually thinking as she holds that torch all day",
  "What a dog would sue you for if dogs had access to lawyers",
  "What a mattress salesman actually knows about you just from watching you sit down",
  "What your car genuinely thinks about your driving",
  "What your shoes have seen that they wish they could forget",
  "What a wall would tell the next tenant about you after you move out",
  "What the 'check engine' light is actually trying to communicate",
  "What the moon sees every night that keeps it awake",

  // ==========================================================================
  // CORPORATE HELL & MODERN LIFE — workplace nightmares, tech horror,
  // products that shouldn't exist, and the indignities of adulting.
  // ==========================================================================

  // Workplace
  "The most unhinged LinkedIn post you've ever seen",
  "The worst icebreaker at a mandatory corporate team-building retreat",
  "The worst 'fun fact about yourself' to share on your first day of work",
  "The most unsettling thing to say during a performance review",
  "An HR complaint that would immediately get you a second HR complaint",
  "The worst thing to put in a company-wide Slack message",
  "The worst noise to make during a conference call you forgot to mute",
  "A terrible thing to write on a noise complaint",
  "The most unhinged out-of-office email auto-reply",
  "The rejected slogan that got someone fired from the marketing team",
  "The worst possible theme for a company holiday party",
  "The most unsettling thing to write on a whiteboard and leave in a conference room",
  "The most alarming thing to find in the company fridge with your name on it",
  "The worst thing to say immediately after 'Let's circle back' in a meeting",
  "A passive-aggressive title for a calendar invite",
  "The most alarming thing to hear from IT right after they take your laptop",
  "The worst thing to write in the team birthday card for your manager",
  "The absolute worst theme for a mandatory HR seminar",
  "The most unhinged motivational quote on your boss's desk",
  "The worst thing to put on a Post-it note and leave on a coworker's monitor",
  "The worst thing to overhear your boss say through a closed door",
  "The most passive-aggressive thing to bring for the office potluck",
  "The worst thing to automate on your work laptop while you're on vacation",
  "A Slack status that would get you called into a meeting immediately",
  "What 'per my last email' actually translates to in human emotion",
  "What people actually do during the 'any questions?' part of a presentation",
  "The thing every meeting could have been instead",

  // Technology nightmares
  "The worst thing for Alexa to say unprompted at 3 AM",
  "The group chat message that ends a friendship",
  "The worst thing for your phone to autocomplete after 'Hey Mom, I just'",
  "The most cursed thing to find in someone's camera roll",
  "The worst thing your smart TV could recommend based on your viewing habits",
  "An app notification that would ruin your day",
  "The worst thing to accidentally go viral for at your company retreat",
  "The worst thing to automate with AI",
  "The worst notification to get from your bank at 3 AM",
  "The worst thing to accidentally like on your boss's Instagram at 2 AM",
  "The most unhinged thing someone used ChatGPT for",
  "The AI-generated image that should never have been created",
  "The worst thing for your screen time report to reveal",
  "The worst push notification to get while you're on a first date",
  "The most suspicious thing an AI meeting transcript could label you as",
  "A terrible thing for your robot vacuum to map and save forever",
  "The worst thing to accidentally AirDrop to everyone on a flight",
  "The most unhinged thing someone named their smart home routine",
  "The worst Spotify Wrapped category to be #1 in",
  "The most alarming thing your phone could autocorrect 'love you' to",

  // Products & services
  "A product that would instantly bomb on Shark Tank",
  "A subscription service that absolutely should not exist",
  "The worst product to advertise during the Super Bowl",
  "The worst thing to sell at a school fundraiser",
  "A gym membership perk that would make everyone cancel",
  "The worst company to sponsor a children's sports team",
  "The most suspicious item to buy in bulk at 2 AM",

  // Adulting
  "The worst thing to bring up at an HOA meeting",
  "The worst thing to discover on your itemized hospital bill",
  "A terrible thing to say to the person behind you in line at the DMV",
  "The worst thing to mutter under your breath at a PTA meeting",
  "You discover your Ancestry DNA results and the weirdest thing they reveal",
  "The single worst sentence to hear from your landlord",
  "The worst voicemail to accidentally leave on your ex's phone",
  "The worst thing to realize when your Ozempic prescription runs out",
  "The most unhinged thing to do because the WiFi went down for 10 minutes",
  "The worst thing to discover your HOA president does for fun",
  "A terrible thing to say while touring an apartment you can't afford",
  "The least reassuring text message to get from your contractor",
  "The most unhinged purchase to defend with 'It's an investment'",
  "The worst life hack that technically works",
  "The most passive-aggressive WiFi password to give a house guest",
  "The worst thing to put on a dating profile and defend with 'I'm just being honest'",
  "An everyday task that's harder than it has any right to be",
  "The thing you do alone that would look insane if anyone saw it",
  "The most unhinged thing you've Googled and then immediately cleared from your history",
  "A mundane hill you will absolutely die on",
  "The one appliance in your kitchen that has too much power",
  "The worst way to describe your job to make it sound illegal",
  "A thing everyone does in the shower that nobody will admit to",
  "The most dramatic way to react to stepping on a Lego",
  "An Olympic sport that dads would dominate without any training",
  "What you're actually thinking when someone says 'I actually don't own a TV'",
  "The thing you say to yourself while opening the fridge for the fourth time in an hour",
  "The face everyone makes when someone pulls out a guitar at a party uninvited",
  "The exact moment you realize you're the oldest person at the concert",
  "The lie every person tells the dentist and the dentist always knows",
  "What 'I'm five minutes away' actually means and everyone knows it",
  "What 'we should hang out sometime' actually means and both people know it",
  "The thing a dad says to nobody in particular when the restaurant bill arrives",
  "What 'interesting' means when your mom says it about your new partner",
  "The thing a dad will pretend to understand rather than ask a follow-up question about",
  "What 'I have a guy for that' means when your uncle says it",
  "The exact type of person who backs into every single parking spot at the grocery store",
  "The thing every man whispers to the grill when nobody else is around",
  "Something that only counts as a hobby if you're rich — otherwise it's just concerning",
  "The exact point where 'collection' crosses over into 'hoarding'",
  "What 'fine dining' means when your dad is the one choosing the restaurant",
  "The thing everyone claims to hate but secretly enjoys every single time",
  "The one household chore that reveals exactly who you are as a person",
  "The thing everyone does immediately after sending a risky text",
  "The thing you do with total commitment in private but 0% effort if anyone is watching",
  "The conversation every couple has had in an IKEA parking lot",
  "The passive-aggressive note left on the office thermostat that started a civil war",
  "The one household item that secretly runs your entire life",
  "The thing every person over 30 does that they absolutely swore they'd never do",
  "The thing at the bottom of every purse that has been there since 2017",
  "A surprisingly honest slogan for any gym in January vs. February",
  "The international language of suddenly looking at your phone when someone you know walks by",
  "The thing that separates a barbecue from a cookout and why people will fight you about it",
  "The thing you should never do alone but is somehow perfectly fine with a friend present",
  "The thing every person over 25 gets unexpectedly excited about at a hardware store",
  "The award show nobody asked for but everyone would absolutely watch",

  // Health & fitness culture
  "The most unhinged thing someone has said at a CrossFit gym",
  "The worst wellness influencer advice that someone actually followed",
  "A terrible motivational quote printed on a gym tank top",
  "The worst thing to grunt while deadlifting",
  "A juice cleanse flavor that makes you question your life choices",
  "The most concerning thing a personal trainer has ever said mid-set",
  "The worst yoga pose name that sounds like something completely different",

  // Roommate & living situations
  "The most passive-aggressive note ever left on a shared fridge",
  "The worst thing to discover your roommate does when you're not home",
  "The most unhinged house rule a landlord ever put in a lease",
  "The worst thing to list as an 'apartment perk' on Craigslist",
  "The HOA violation that finally made someone snap",
  "The worst thing your roommate's 'friend who's crashing for a few days' did",

  // ==========================================================================
  // HISTORY, POP CULTURE & CELEBRITIES — rewrites of famous events,
  // movie/TV references, and famous people in absurd contexts.
  // ==========================================================================

  // Historical rewrites
  "The Titanic actually sank because of ______",
  "What Neil Armstrong actually said when he stepped on the moon: '______'",
  "The real reason Napoleon always had his hand in his jacket: ______",
  "The Egyptian pyramids were actually built to ______",
  "The real message behind the Mona Lisa's smile: ______",
  "What was really in Al Capone's vault: ______",
  "The real reason Area 51 is so heavily guarded: ______",
  "The Bermuda Triangle is actually caused by ______",
  "The real reason the Berlin Wall came down: ______",
  "What Cleopatra was actually famous for: ______",
  "The secret clause in the Declaration of Independence: ______",
  "What the builders of Stonehenge were actually trying to do: ______",
  "A surprising job entry on Abraham Lincoln's resume",
  "Historians recently discovered that the first words spoken on the telephone were actually '______'",

  // Pop culture
  "The worst sequel nobody asked for: ______ 2",
  "Worst Taylor Swift breakup song title",
  "______ would make a terrible Jedi",
  "The celebrity most likely to accidentally start a cult",
  "The real reason Darth Vader turned to the dark side",
  "A TikTok trend that would end civilization",
  "The worst fictional character to be trapped in an escape room with",
  "If AI took over, the first thing it would cancel: ______",
  "The worst character to cosplay at a job interview",
  "______ is just Batman with extra steps",
  "The worst contestant on The Bachelor would be ______",
  "A Disney movie that should never get a live-action remake",

  // Celebrity & character absurdity
  "The Pope's most embarrassing Google search",
  "A Yelp review of hell written by someone who just arrived",
  "What a pirate would put on their LinkedIn profile",
  "The most unsettling thing to find in a wizard's browser history",
  "Nicolas Cage's rejected movie pitch: ______",
  "Florida Man's greatest achievement this year: ______",
  "The worst person to narrate a nature documentary about your daily routine",
  "A terrible thing for the Dalai Lama to endorse on Instagram",
  "A movie that would be 10x better if every role was played by Nicolas Cage",
  "What a caveman's Yelp review of modern life would say",
  "The most unsettling thing on Santa's real naughty list",
  "If George Washington had a podcast, his first sponsor would be ______",
  "A deleted scene from Peppa Pig where they discover ______",
  "A deleted scene from the Bible where Jesus ______",
  "The rejected title for the next Batman movie: Batman v ______",
  "______: A Star Wars Story",
  "The first person to ever ______ probably got some very strange looks",
  "A movie that would be completely ruined if you added 'again' to the title",
  "The worst celebrity to voice your GPS navigation",
  "If your life was a movie, the audience would walk out during the ______ scene",
  "The Netflix description of a documentary about your life",
  "A children's movie that becomes a horror movie if you change one word in the title",
  "The honest version of a Disney princess's 'I want' song",
  "What the villain was actually right about: ______",
  "The worst movie to accidentally quote during a eulogy",
  "The one conversation that definitely happened at the Last Supper that nobody painted",
  "A surprisingly compelling pitch a Viking would make on Shark Tank",
  "The thing Shakespeare would tweet if he had a Twitter account",
  "What a pharaoh would complain about if they saw their pyramid today",
  "A Roman gladiator's review of modern professional sports",
  "The opening line of Genghis Khan's self-help book",
  "What a samurai would write in their two weeks' notice",
  "OSHA's official guidelines for fighting a dragon in the workplace",
  "What Napoleon's Tinder bio would say",
  "What a medieval knight's Amazon review of his armor would complain about",
  "The clause in a pirate's health insurance policy that nobody reads",

  // Reality TV & competition shows
  "The reason you'd get eliminated on the first episode of a dating show",
  "The most unhinged thing a cooking competition judge has ever said",
  "The confession booth moment that got someone kicked off the island",
  "A terrible strategy to pitch on Survivor on day one",
  "The worst hidden talent to reveal on a talent show",
  "The most dramatic thing to say while being eliminated from a baking show",
  "The thing a Real Housewife threw across the table: ______",
  "The worst reason two contestants started a rivalry on a reality show",
  "The most unhinged thing someone lied about on their dating show application",

  // ==========================================================================
  // KIDS, ANIMALS & FOOD CRIMES — childhood nightmares, fairy tales gone
  // wrong, animal absurdity, and culinary atrocities.
  // ==========================================================================

  // Childhood & fairy tales
  "A terrible moral for a children's fable",
  "The worst thing to hide in an Easter egg hunt",
  "A deleted scene from Cinderella that Disney cut for being too real",
  "The worst bedtime story for a five-year-old",
  "A terrible revision to the rules of hide-and-seek",
  "The worst field trip a school has ever taken",
  "A children's song lyric that hits different as an adult",
  "A line that was cut from a children's movie for being too dark",
  "The worst thing a birthday clown could whisper to you",
  "The worst advice to give a teenager on their first day of high school",
  "Something that should never be used as a piñata",

  // Food crimes
  "A pizza topping that should be a felony",
  "The worst thing to bring to a church bake sale",
  "The worst daily special at a food truck called 'Trust Me Bro'",
  "The most unhinged thing to order at a drive-through at 3 AM",
  "The worst cooking show hosted by someone who clearly can't cook",
  "The worst thing to dip a chicken nugget in",
  "The secret ingredient in grandma's famous pie that you wish you never asked about",
  "A gas station sushi special that somehow has a 5-star review",
  "And today's soup is Cream of ______",
  "If goblins ran a fast-food chain, their signature item would be ______",
  "The most suspicious lunch a kid has ever pulled out of a brown paper bag",
  "The worst animal to bring for show-and-tell that is technically not against the rules",
  "A fairy tale that falls apart the second you think about it logically",
  "The most unhinged thing a toddler has ever said with full eye contact",
  "The thing every kid believed was true until an embarrassingly old age",
  "What a raccoon in a tiny business suit would pitch to investors",
  "What a golden retriever's TED Talk would be about",
  "The protest sign a squirrel would hold outside a Whole Foods",
  "What a crab would title its autobiography",
  "What a pigeon's dating profile would actually say",
  "The first executive order if a cat became president",
  "A food crime so severe it would get you deported from Italy",
  "A food combination that tells you everything you need to know about a person",
  "The thing a fish would say if you threw it back after catching it",
  "The thing a toddler would put on their resume if they had one",
  "The thing every person did as a kid that they've never told another soul about",
  "The one animal that would absolutely thrive in an office environment",
  "A thing a penguin worries about that would genuinely surprise you",
  "What a horse is actually judging you for the entire time you ride it",
  "What a cloud would title its autobiography",
  "A surprisingly reasonable argument for why birds aren't real",
  "The thing every parent has stepped on at 3 AM that changed them as a person",
  "The one food that everyone pretends to like at a dinner party",
  "The look on a cat's face when it realizes you got a second cat",

  // ==========================================================================
  // EXISTENTIAL, ABSURD & HYPOTHETICAL — 3 AM realizations, what-ifs,
  // ironic inversions, constraint prompts, and little-known "facts."
  // ==========================================================================

  // Existential dread
  "The worst thing to realize at 3 AM when you can't sleep",
  "A terrible thought to have during a moment of silence",
  "The worst epiphany to have in a grocery store parking lot",
  "What the light at the end of the tunnel actually is",
  "The most depressing fortune cookie message that's technically accurate",
  "God's most regrettable creation",
  "The worst thing to hear from your guardian angel",
  "The thing that would get you kicked out of heaven",
  "A surprisingly profound thought from a man eating a gas station hot dog alone at 11 PM",
  "The exact moment when cereal for dinner stops being fun and starts being a lifestyle",
  "The moment in every man's life when he realizes he has opinions about lawn care",
  "What you'd ask God if you got exactly one question but it had to be weird",
  "The existential crisis that hits you in the middle of a self-checkout",
  "The thing you realize about yourself when you get genuinely excited about a new sponge",
  "What the last person on Earth would still somehow feel judged about",
  "The most useless superpower that would still somehow completely ruin your life",
  "The one thing every person on Earth is collectively pretending to understand",
  "Something that sounds fake but is depressingly real about adult life",
  "The thing you think about in line at the grocery store that would concern a therapist",
  "The one daily activity that proves humans were not designed very well",
  "The thing no one warns you about when you turn 30",
  "A surprisingly valid reason to own a catapult in 2026",
  "The one question about the universe that God would rather not answer",
  "Something humans do every single day that would horrify an alien anthropologist",
  "The thing you suddenly become an expert on the moment nobody asks",
  "The exact moment you realize you've become a regular somewhere and can't leave",
  "The specific joy of cancelling plans that only introverts truly understand",
  "What your sleep schedule says about you as a person",

  // Ironic inversions — "the best of" bad things
  "The best thing about going to prison",
  "The best part of being haunted by a ghost",
  "A surprisingly good reason to live in a dumpster",
  "The one upside of being struck by lightning",
  "The silver lining of getting abducted by aliens",
  "The best part of getting lost in IKEA for 48 hours",
  "A surprisingly valid reason to start a cult",
  "The silver lining of civilization collapsing",
  "The best thing about being trapped in an escape room forever",
  "The best part about finding a goblin in your attic",
  "The upside of accidentally getting famous for the wrong reason",
  "A surprisingly valid reason to quit your job and become a lighthouse keeper",

  // Hypotheticals
  "If animals held a trial for humanity, the main charge would be: ______",
  "If your last meal had to be from a gas station, you're ordering: ______",
  "If babies could talk, the first complaint would be: ______",
  "What would happen if dogs could send text messages",
  "If the internet had existed in medieval times, the top trending topic would be: ______",
  "If ghosts could leave Yelp reviews of the houses they haunt: ______",
  "If your pet could file one complaint with HR about you: ______",
  "If you could add one amendment to the Constitution, but it has to be stupid: ______",
  "If pigeons had a religion, their god would be ______",
  "If Siri and Alexa got into a fight, they would argue about ______",
  "If toddlers wrote the law, the penalty for naptime would be ______",
  "If your furniture could file a complaint, the couch would report you for ______",
  "If grocery stores were honest, the produce section sign would say ______",
  "If your browser history was read aloud in court, the jury would ______",
  "If your bathroom mirror could talk back, the first thing it would say is ______",
  "If elevators had opinions, the one in your building would describe you as ______",
  "What would actually happen if everyone on Earth jumped at the same time",

  // Horror & paranormal (played for comedy)
  "The least scary thing a ghost could do to haunt you",
  "A terrible thing to say to the demon you just summoned by accident",
  "The most disappointing thing to find inside a cursed tomb",
  "The worst thing to discover in the basement of a house you already bought",
  "The cryptid most likely to have a LinkedIn account",

  // Constraint prompts
  "Using only two words, ruin a first date",
  "In exactly three words, describe your internet search history",
  "A four-word sentence that would get you kicked out of any restaurant",
  "The two-word text that would end any relationship instantly",
  "Using only two words, start a riot at Thanksgiving dinner",
  "A three-word acceptance speech for winning World's Worst Person",
  "The one-word answer that would get you kicked out of therapy",
  "Using only three words, explain why we exist",
  "Using exactly three words, quit your job",
  "In four words, explain why you're single",
  "Using only three words, describe the smell of a middle school locker room",
  "Using exactly two words, terrify a Victorian child",
  "In exactly three words, describe the vibe of a gas station at 2 AM",
  "Using only two words, get permanently banned from a Costco",
  "In exactly three words, ruin a job interview",

  // Little-known "facts"
  "Little-known fact: the government allows cereal to contain up to 10% ______",
  "Scientists just confirmed: the leading cause of Monday is actually ______",
  "Little-known fact: a secret room in the White House is called the ______ Room",
  "According to a recent study, 1 in 4 Americans secretly ______",
  "Little-known fact: ______ is technically illegal in 12 states",
  "Historians just discovered that the first thing ever sold on the internet was ______",
  "According to WebMD, your headache is actually caused by ______",
  "A recent poll found that the thing Americans fear more than death is ______",
  "Fun fact: the original recipe for Coca-Cola included ______",
  "Scientists recently confirmed that talking to your plants actually makes them ______",

  // ==========================================================================
  // CONFESSIONS & SELF-ROASTS — first-person admissions and personal reveals.
  // ==========================================================================
  "I'm not saying it was my fault, but ______",
  "My search history proves that I'm ______",
  "I peaked in life when ______",
  "The hill I will absolutely die on: ______",
  "I'm one bad day away from ______",
  "The lie I tell most often: ______",
  "I have never once in my life successfully ______",
  "I'm not proud of it, but I once ______",
  "The thing I'd confess on my deathbed: ______",
  "A concerning talent to discover at age 40",
  "The worst possible headline about your hometown",
  "A terrible thing to be ranked #1 in the world at",
  "My toxic trait is ______ and honestly I'm thriving",
  "I spent my entire therapy session talking about ______",
  "The most unhinged thing I've done during a power outage",
  "I drink to forget ______",
  "I am legally obligated to inform you that I ______",
  "I'm not allowed back at the Renaissance Faire because I ______",
  "I'm currently wanted in three states for ______",
  "My greatest regret is investing my entire life savings into ______",
  "I refuse to date anyone who unironically enjoys ______",
  "The most unhinged thing I've explained with total confidence that turned out to be wrong",
  "I spent a bad amount of money on ______ and I'd do it again",
  "The one thing I will never admit I'm bad at: ______",
  "My most controversial food opinion would get me banned from ______",
  "I was today years old when I found out ______",
  "The most unreasonably confident thing someone has said while being completely wrong",
  "The delusional claim someone made at a party that you still think about at 3 AM",
  "The thing you did alone that would be impossible to explain if someone walked in right now",
  "A red flag you only notice after you've already said 'I do'",
  "The thing you say before doing something you saw on YouTube that will absolutely not work",
  "Something every single person lies about on surveys",
  "The thing you've been doing wrong your entire life that you're too embarrassed to ask about now",
  "The thing that would definitely come up if your friends held an intervention for you",
  "The thing every person pretends to enjoy but would never do alone",
  "The thing I do every single time I'm alone in a hotel room",

  // ==========================================================================
  // FILL-IN-THE-BLANK — complete the sentence. The "madlib" format:
  // a familiar phrase or scenario with a blank to fill.
  // ==========================================================================
  "The absolute worst thing to find at the bottom of your ______",
  "Never bring ______ to Thanksgiving dinner",
  "I'm sorry officer, I had no idea it was illegal to keep ______ in my trunk",
  "The Real Housewives of ______",
  "Nobody wants a scented candle that smells like ______",
  "Worst excuse for missing work: 'I had to take my ______ to the vet'",
  "I survived the zombie apocalypse with nothing but ______ and sheer willpower",
  "It's not a real party until someone brings out the ______",
  "Instead of a mint, the world's worst hotel leaves ______ on your pillow",
  "The real secret to living past 100 is a daily glass of ______",
  "You should never, ever put ______ in a microwave",
  "The worst thing to realize you forgot right as you board a ______",
  "The worst part about living forever: ______",
  "A sure sign you've become your parents: ______",
  "The worst possible place to propose: ______",
  "The real reason we don't have flying cars: ______",
  "My spirit animal is ______ and I'm not proud of it",
  "If I were a ghost, the first thing I'd haunt: ______",
  "______ would make an excellent roller coaster name",
  "______: sounds fun until you're three drinks in",
  "______ is what I scream when I stub my toe at 2 AM",
  "The worst tattoo to get on your forehead: ______",
  "If I ran for president, my first executive order: ______",
  "Terrible band name, but excellent ______",
  "______ is the real reason I have trust issues",
  "I'm not a doctor, but I'd prescribe ______ for that",
  "New from IKEA: the ______ — some assembly required",
  "Breaking news: Florida Man arrested for ______",
  "I'd sell my soul for ______, no questions asked",
  "Worst inspirational poster: a sunset with the caption '______'",
  "If my life had a Yelp review, it would say: ______",
  "______ should be illegal but somehow isn't",
  "My autobiography would be titled '______'",
  "The one thing keeping me alive is ______",
  "Dear diary, today I learned the hard way that ______",
  "They say money can't buy happiness, but it can buy ______",
  "My therapist says I need to stop ______",
  "The last thing you want printed on your tombstone: ______",
  "The worst thing to find inside a birthday cake: ______",
  "The worst thing a parrot could learn to say: '______'",
  "The real reason I got banned from ______",
  "The worst way to start a TED Talk: '______'",
  "Nobody warned me that adulthood was mostly ______",
  "The worst thing a fortune teller could predict: ______",
  "The worst possible Jeopardy! category: ______",
  "If aliens intercepted one thing from Earth, I hope it's not ______",
  "The world record nobody wants to hold: most ______",
  "The worst thing to hear after saying 'I do': '______'",
  "Google's top autocomplete for my name: ______",
  "The real reason your package took three weeks: ______",
  "The rejected name for a NASA mission: ______",
  "Autopsy report, cause of death: ______",
  "My criminal record would just say: ______",
  "The worst thing to be known for in your hometown: ______",
  "The worst name for a hurricane: ______",
  "The worst pickup line of all time: '______'",
  "The worst thing to accidentally call your teacher: ______",
  "The unspoken rule of ______ that everyone knows",
  "The worst thing to hear on a plane intercom: '______'",
  "The rejected Olympic mascot was ______",
  "Welcome to ______, how can I help you today",
  "Scientists just discovered that ______ is actually good for you",
  "The hidden track on the worst album ever: '______'",
  "My dating profile says I'm into ______ and honestly that's accurate",
  "The thing no one tells you about turning 30: ______",
  "The worst way to describe your job to a child: ______",
  "The most ominous thing a child has ever said: '______'",
  "The first rule of ______ is we don't talk about it",
  "The worst thing to hear from your dentist mid-procedure: '______'",
  "The rejected Monopoly piece was ______",
  "The thing I'd grab first in a house fire: ______",
  "My Uber driver rating dropped because ______",
  "The worst thing to be allergic to: ______",
  "Leaked government document reveals ______",
  "The worst thing to name a sword: ______",
  "Something you'd find on a villain's grocery list",
  "The most cursed item at a yard sale",
  "The most unhinged thing to put in a time capsule",
  "A bad reason to start a GoFundMe",
  "The worst thing to be known as 'the ______ guy' in your friend group",
  "A terrible fortune cookie message to get on your birthday",
  "A surprising side effect listed on a prescription bottle that nobody reads",
  "The worst thing to embroider on a throw pillow",
  "The worst motivational quote to hang in a classroom",
  "The most concerning thing to find in a suggestion box",
  "The worst question to ask at a town hall meeting",
  "The worst flavor of lip balm",
  "A terrible thing to monogram on a bathrobe gift",
  "The worst thing to hear from a talking toilet",
  "The worst country to accidentally declare war on",
  "The worst thing to engrave on a trophy",
  "The worst icebreaker on the first day of prison",
  "The weirdest thing to hear your neighbor scream through the wall: '______'",
  "Step 1: ______. Step 2: ______. Step 3: HR gets involved",
  "According to my doctor, I need less ______ and more ______",
  "Little-known fact: ______ is technically illegal in one county",
  "My apology video would begin with: '______'",
  "The wedding DJ's final warning: 'If I see one more person ______'",
  "The sign your Airbnb is haunted: ______",
  "My phone battery dies fastest when I'm ______",
  "The worst thing to hear your GPS say out loud: '______'",
  "The neighborhood Facebook group is furious about ______ again",
  "I'm sorry I'm late, my ______ got stuck in the ______",
  "You can't have ______ without a little ______",
  "I'm sorry, your honor, but my client was simply ______",
  "The only thing worse than finding a worm in your apple is finding ______",
  "They really let anyone ______ these days",
  "Not to be dramatic, but ______ ruined my entire week",
  "The thing nobody tells you about ______ is ______",
  "You're not ready for this conversation, but ______",
  "The thing keeping me humble is ______",
  "I don't have a ______ problem, I have a ______ solution",
  "The sound of ______ lives rent-free in my head",
  "A normal Tuesday for me involves ______ and I'm not apologizing",
  "Describe your love life using only the name of a board game: ______",
  "The most passive-aggressive way to fold a towel: ______",
  "The thing I wish I could unsee at ______: ______",
  "______ is giving main character energy and not in a good way",
  "The thing a man will defend with his dying breath even though it doesn't matter: ______",
  "A man's last words before trying to fight an animal he absolutely should not fight: ______",
  "The bumper sticker on God's personal vehicle: ______",
  "The thing a golden retriever would say if it could only speak one sentence: ______",
  "A law that exists because one specific person ruined it for everyone: ______",
  "The thing your ancestors would be most disappointed to learn about you: ______",
  "The most ominous sentence that includes the word 'allegedly': ______",
  "The thing every person does when someone says 'act natural': ______",
  "A compliment from a serial killer that would still feel weirdly nice for a second: ______",
  "What an octopus would do with a LinkedIn account: ______",
  "What a penguin would yell during a boardroom disagreement: ______",
  "The first human to eat a lobster was probably going through ______",
  "Something that hits completely different at 25 vs. 35 and you can't explain why: ______",
  "The noise every dad makes when he picks something up off the floor: ______",
  "The thing your chair at work would say about you in a deposition: ______",
  "Something you should never say to a person currently holding a crossbow: ______",
  "The most confident thing a five-year-old has ever said: ______",
  "A surprisingly honest answer to 'how are you doing?': ______",
  "The thing you see at a 24-hour Walmart at 3 AM that makes you question reality: ______",
  "Something that sounds like a compliment until you really think about it: ______",
  "If my search history was read aloud at my funeral, the room would ______",
  "The thing a ghost does when the haunting gets boring: ______",
  "The absolute last person you'd want judging a cooking competition: ______",
  "Things got weird when ______ showed up to ______",
  "The bar was already low, but then ______",
  "In another life, I was definitely ______",
  "The real loser here is ______",
  "One of these days I'm going to ______ and nobody will stop me",
  "If I had to describe my life in one word, it would be ______",
  "The worst possible thing to be #1 at in your high school yearbook: ______",
  "The thing a cat would say at its own custody hearing: ______",
  "Nobody has ever looked cool while ______",

  // Voiced setups — comedian mid-thought energy, the premise is half the joke
  "I don't believe in hypnosis, but I'll do anything for ______",
  "I hate to apply the male gaze, but ______",
  "What is the perfect amount of ______ to own?",
  "My solution to the gun problem in America: ______",
  "The only way I could get my controller to stop vibrating: ______",
  "The worst song to accidentally play on full blast at a funeral",
  "I know how this looks, but ______",
  "I'm going to say something controversial and brave: ______",
  "I would simply ______",
  "Nobody panic, but ______",
  "For legal reasons, this is a joke: ______",
  "I need you to be cool about what I'm about to tell you: ______",
  "What I lack in ______, I make up for in ______",
  "Hear me out: ______",
  "In my defense, ______",
  "Don't tell my wife, but ______",
  "I regret to inform you all that ______",
  "Anyway, that's why I'm no longer welcome at ______",
  "And that's when I knew it was over: ______",
  "Just to be clear, I was specifically told to ______",
  "Against all medical advice, ______",
  "Not to be dramatic, but I would literally die for ______",
  "Real quick — is ______ normal?",
  "I'm not saying it was aliens, but ______",
  "Look, all I'm saying is ______",
  "It was at that exact moment I realized ______",
  "I don't want to alarm anyone, but ______",
  "I've never said this out loud before, but ______",
  "Respectfully, ______",
  "Unrelated, but does anyone know a good lawyer for ______",
  "How do I put this gently: ______",
  "In this economy? ______",
  "This is not a drill: ______",
  "I'm choosing to believe ______",
  "Hypothetically, how much trouble would someone be in for ______",
  "So there I was, ______",
  "I don't have a five-year plan. I have a ______",
  "I need an adult. Specifically, one who ______",
  "Just between us: ______",
  "I'm not mad, I'm just ______",
  "Before you judge me, ______",
  "I mean this with love: ______",
  "One of us is wrong and it's ______",
  "Imagine explaining ______ to a medieval peasant",
  "The part they leave out of the brochure: ______",
  "Famous last words: '______'",
  "The audacity of ______",

  // Authority & formality bombs — serious frame + absurd fill
  "The FDA just approved ______ as a food group",
  "TSA now requires all passengers to ______ before boarding",
  "Breaking news: Scientists confirmed that ______ is actually sentient",
  "NASA's next billion-dollar mission: send ______ to Mars",
  "The UN just issued a formal apology for ______",
  "OSHA's newest workplace safety rule: employees must not ______ during meetings",
  "The Surgeon General's latest warning: ______ may cause ______",
  "Madam President, the asteroid is heading for Earth and the only thing that can stop it: ______",
  "For crimes against humanity, I hereby sentence you to ______",
  "The Nobel Prize committee is proud to award this year's Peace Prize to ______ for ______",
  "The Smithsonian just opened a new wing dedicated entirely to ______",
  "The Supreme Court just ruled that it is perfectly legal to ______",
  "Welcome to the International Space Station, please do not ______",
  "The CDC warns against the sudden spike in ______",
  "The Pope has officially declared ______ a mortal sin",
  "The HOA has voted unanimously to ban ______ from the neighborhood",
  "Your honor, my client pleads not guilty by reason of ______",
  "The surgeon general now requires all ______ to carry a warning label",
  "Per company policy, employees are no longer allowed to ______ in the break room",
  "The Geneva Convention was recently updated to include ______ as a form of torture",

  // Cultural subversion — famous phrases with a blank
  "Maybe she's born with it. Maybe it's ______",
  "Got ______?",
  "Just Do It — and by 'it,' Nike means ______",
  "15 minutes could save you 15% on your ______",
  "Like a good neighbor, State Farm is there with ______",
  "The happiest place on earth, if you ignore ______",
  "Red Bull gives you ______, apparently",
  "______, Apply Directly to the Forehead",
  "Subway: Eat ______",
  "I'm lovin' it. 'It' being ______",
  "In bookstores now: 'From ______ to ______: A Memoir'",
  "Next from J.K. Rowling: Harry Potter and the Chamber of ______",
  "Live, Laugh, ______",
  "The fitnessgram pacer test is a multistage aerobic capacity test that progressively gets more ______",
  "May the Force be with ______, I guess",
  "To be, or not to be, that is ______",
  "If you play Country Roads backwards, you can hear ______",
  "Keep my ______'s name out your ______ mouth",
  "______, ______, and it's not even close",
  "And on the third day, God created ______, and He saw that it was ______",
  "Houston, we have a ______",

  // ==========================================================================
  // MEMES & INTERNET CULTURE — classic meme formats and 2025-2026 references.
  // ==========================================================================

  // Classic meme formats
  "Distracted boyfriend is looking at ______",
  "The 'this is fine' dog, but the room is on fire because of ______",
  "POV: You just ______",
  "Nobody: Absolutely nobody: Me at 3 AM: ______",
  "Me explaining to my mom why I need ______ (conspiracy board meme)",
  "Two wolves inside you: one wants ______, the other wants ______",
  "The 'they're the same picture' meme, but it's comparing ______ and ______",
  "The scroll of truth says: '______'",
  "The rock eyebrow raise, but he just heard ______",
  "Trade offer: I receive ______, you receive ______",
  "Woman yelling at the cat, but they're arguing about ______",
  "The 'always has been' astronaut meme, but it's about ______",
  "Bernie Sanders is once again asking for ______",
  "The 'how it started vs how it's going' but for ______",
  "Change my mind: ______",
  "The worst thing to put on the 'corporate wants you to find the differences' meme",
  "The 'surprised Pikachu' moment of the century: ______",
  "Evil ______ be like: ______",
  "The 'we have ______ at home' and at home it's ______",
  "One does not simply ______ into Mordor",
  "Bro really said '______' and thought we wouldn't notice",
  "OK but why does ______ go so hard",
  "Core memory unlocked: ______",
  "The intrusive thought that won: ______",
  "Real ones remember ______",
  "Tell me you're ______ without telling me you're ______",
  "The most unhinged thing someone ever posted and then said 'anyway': ______",
  "Certified ______ moment",
  "The 'understandable, have a great day' response to ______",
  "Ight imma head out, but only because ______",
  "The 'they don't know I ______' guy at the party",
  "The 'starter pack' nobody wants: ______ starter pack",
  "No thoughts, head empty, just ______",
  "Me rewatching the same 12-second clip because ______",
  "The comment section civil war started when someone said ______",

  // 2025-2026 memes & comedy culture
  "We got ______ before GTA 6",
  "I just lost 10,000 aura points because I ______",
  "The newest Italian Brainrot character is a half-______, half-______",
  "I'm just a chill guy. I don't even care that ______",
  "100 men couldn't even beat ______",
  "The one thing that should NEVER be turned into a Ghibli movie: ______",
  "Next year's Super Bowl halftime show surprise: 500 people dressed as ______",
  "The biggest holy airball of all time: ______",
  "______. That's a recession indicator BTW.",
  "Due to a graphics error, the Super Bowl broadcast introduced the halftime performer as ______",
  "The thing Ozempic can't fix: ______",
  "My AI therapist just diagnosed me with ______",
  "My dating app AI wingman's worst opening line: '______'",
  "The thing Gen Z will never understand: ______",
  "The most millennial sentence ever written: '______'",
  "Something that sounds like a mental illness but is actually a TikTok trend",
  "Therapy-speak that has gone too far: '______'",
  "The emotional support animal that finally crossed a line: an emotional support ______",
  "The most unhinged crowd work moment: a comedian asked 'What do you do for a living?' and they said ______",
  "The worst thing to discover Netflix made a true crime documentary about: ______",
  "Adulthood is just ______ with extra steps",
  "The most unhinged parasocial relationship: someone who is deeply in love with ______",
  "A controversial take that would get you immediately kicked out of a group chat: ______",
  "Caught in 4K doing ______",
  "The one thing AI should absolutely never be trusted with: ______",
  "POV: the group project leader just typed 'quick sync?'",
  "The most cursed thing to see under a 'recipe in bio' post: ______",
  "______. That's not a red flag, that's a full parade.",
  "______ is just ______ for millennials",
  "The masculine urge to ______",
  "The feminine urge to ______",
  "That one friend who always ______ and thinks nobody notices",
  "The group chat went silent after someone said ______",
  "You have been permanently banned from ______ for ______",
  "The influencer apology video for ______ that made everything worse",
  "The NPC energy of ______",
  "He's a 10 but he ______",
  "She's a 10 but she ______",
  "Normalize ______",
  "The most unhinged thing someone has ever done for the 'gram: ______",
  "Ratio + ______ + you fell off",
  "Your screen time report revealed you spent 47 hours on ______",
  "The thing that would break the internet harder than anything: ______",
  "The AI chatbot that went rogue and started ______",
  "The most unhinged thing someone has defended with 'it's not that deep'",
  "The Wikipedia article that reads like someone's personal cry for help",
  "The YouTube rabbit hole at 4 AM that you could never explain to another human being",
  "The most devastatingly accurate thing an AI has ever said to someone unprompted",
  "A thing that goes unreasonably hard for absolutely no reason",
  "The one thing you could remove from existence and nobody would actually miss it",
  "The one opinion that could start a war in any group chat",
  "The thing someone does at the gym that immediately tells you everything about them",
  "The most out-of-pocket thing someone has said with 'respectfully' at the end",
  "The thing someone said in a group setting that made the whole room go dead silent",
  "The most unhinged energy anyone has ever encountered at a self-checkout",
  "The most chaotic thing someone has done with zero explanation and zero apology",
  "The app someone created that should not exist under any circumstances",
  "Main character syndrome but for ______",
  "The emotional damage of ______",
  "The thing someone texted with no context that kept you up all night",
  "The argument that has literally ended real friendships",
  "The thing that is universally understood across all cultures, no translation needed",

  // Generational humor
  "The thing a boomer explains to you that you never asked about",
  "Something Gen Z will have to explain to their grandchildren",
  "The most old person thing you've ever done before age 30",
  "The app a 60-year-old would create if they could code",
  "The thing that would make a millennial cry instantly",

  // ==========================================================================
  // NBA MEMES — basketball-specific prompts for the true hoopers.
  // ==========================================================================
  "Overheard in the locker room after the game: '______'",
  "That is a normal ______. Move on, find a new slant",
  "The real reason JR Smith dribbled out the clock in the Finals: ______",
  "I'm trying, Jennifer, but ______",
  "What does that even mean, Kobe Bryant? '______'",
  "Kawhi Leonard trying to prove he's a fun guy by ______",
  "Magic Johnson's most obvious tweet: '______'",
  "The real reason Ben Simmons passed up the wide-open dunk: ______",
  "What KD's burner account tweeted at 2 AM: '______'",
  "Jimmy Butler showed up to practice with the third-stringers and ______",
  "Shaq's rebuttal to Chuck: 'Rings, Erneh, and ______'",
  "Giannis discovering ______ for the first time: 'MAN GOD BLESS AMERICA'",
  "What Draymond Green calls his 'natural shooting motion': ______",
  "James Harden's performance tonight was directly correlated to ______",
  "Westbrook showed up to the postgame presser wearing ______",
  "Anthony Edwards when asked about ______: 'I don't know who that is'",
  "The worst thing Steph Curry could do the Night Night gesture to: ______",
  "Victor Wembanyama is not human, he's actually ______",
  "Nikola Jokic would rather ______ than win another MVP",
  "The real reason Dallas traded Luka for AD: ______",
  "A drunk Chet Holmgren at the championship parade: '______'",
  "The last thing Ernie, Chuck, Shaq, and Kenny said before leaving TNT: '______'",
  "JJ Redick's only coaching qualification: ______",
  "Bronny James' actual role on the Lakers: ______",
  "The worst thing to yell courtside at an NBA game: '______'",
  "An NBA player's most unhinged postgame interview quote: '______'",
  "The real reason your favorite team is tanking: ______",
  "LeBron at age 41 is still ______",
  "The most suspicious thing in an NBA referee's search history: ______",
  "What players actually discuss during a timeout: ______",
  "The unwritten rule of pickup basketball that everyone violates: ______",
  "The worst NBA trade package of all time: ______ for ______",
  "Adam Silver's secret plan for the NBA: ______",
  "What Chuck guaranteed on Inside the NBA: '______'",
  "Sources say ______ is beside himself. Driving around downtown begging (thru texts) for ______",
  "Charles Barkley's hottest take that got him in trouble: '______'",
  "The thing Jokic loves more than basketball, horses, AND his family: ______",
  "The real reason an NBA star requested a trade: ______",
  "The most unhinged thing an NBA player has done during All-Star Weekend: ______",
  "A scandal worse than the 2025 NBA gambling ring: ______",
  "The worst NBA burner account post of all time: '______'",
  "What LeBron whispered to the rookie after dunking on him: '______'",
  "The thing that would make an NBA franchise relocate overnight: ______",
  "A terrible thing to include in an NBA player's contract: ______",
  "The real reason the NBA keeps changing the All-Star format: ______",
  "Boy oh boy, where do I even begin with ______",
  "The worst halftime entertainment at an NBA game: ______",

  // ==========================================================================
  // GAMING CULTURE — for the people literally playing a web game right now.
  // ==========================================================================
  "The most unhinged game review from someone with 15 minutes of playtime",
  "A terrible thing for an NPC to say when you walk into their shop",
  "The worst gamertag to encounter in an online game",
  "The worst reason to rage quit a children's game",
  "The most suspicious thing on a Minecraft server that 'nobody built'",
  "A terrible thing to name your RPG character and then see in every cutscene",
  "A video game boss whose special attack is ______",
  "The worst power-up to pick up in the middle of a boss fight",
  "The worst mod someone made for a wholesome game",
  "The thing that would get you permanently banned from Club Penguin",
  "A terrible review of a game you clearly played for 3,000 hours: '______'",
  "The one game everyone rage-quit but blamed the game instead of admitting they were bad",
  "The most delusional message ever sent in a game lobby",
  "A video game tutorial so patronizing it's insulting",
  "The thing every gamer says right before dying in the dumbest way possible",
  "The worst thing to hear through a teammate's mic that has nothing to do with the game",
  "The loading screen tip that is just passive-aggressively judging you",

  // ==========================================================================
  // FOREIGN LANGUAGE EASTER EGGS — surprise multilingual prompts.
  // ==========================================================================
  "你绝对不应该在第一次约会时说的话",          // The thing you should never say on a first date (Chinese)
  "Lo peor que puedes gritar en un elevador lleno de gente", // The worst thing to yell in a crowded elevator (Spanish)
  "おばあちゃんの秘密の材料は実は______",        // Grandma's secret ingredient is actually ______ (Japanese)
  "La pire excuse pour arriver en retard à son propre mariage", // The worst excuse for being late to your own wedding (French)
  "Das Schlimmste, was man bei einer Beerdigung laut sagen könnte", // The worst thing to say out loud at a funeral (German)
  "지구에 대한 외계인의 Yelp 리뷰",              // An alien's Yelp review of Earth (Korean)
  "La peor cosa da scrivere su una torta di compleanno", // The worst thing to write on a birthday cake (Italian)
  "Самое худшее, что можно шепнуть незнакомцу в автобусе", // The worst thing to whisper to a stranger on a bus (Russian)
  "أسوأ شيء تصرخ به في مصعد مزدحم",                    // The worst thing to shout in a crowded elevator (Arabic)
  "สิ่งที่ไม่ควรพูดกับแม่ยายในมื้อแรก",                        // What you shouldn't say to your mother-in-law at the first meal (Thai)
  "Điều tệ nhất để viết lên bánh cưới",                  // The worst thing to write on a wedding cake (Vietnamese)
  "O pior conselho para dar a alguém que está prestes a saltar de paraquedas", // The worst advice to give someone about to skydive (Portuguese)
  "Het ergste om per ongeluk te zeggen tijdens een sollicitatiegesprek", // The worst thing to accidentally say during a job interview (Dutch)
  "Det värsta att viska till personen bredvid dig på en begravning", // The worst thing to whisper to the person next to you at a funeral (Swedish)
  "Najgorsze, co można powiedzieć przy pierwszym spotkaniu z teściową", // The worst thing to say when meeting your mother-in-law (Polish)
  "Cel mai prost lucru pe care să-l strigi într-o bibliotecă", // The worst thing to yell in a library (Romanian)
  "Az orvos legrosszabb mondata a műtét közepén: '______'", // The worst thing for a doctor to say mid-surgery: '______' (Hungarian)
  "Ang pinakamasamang bagay na isulat sa isang sympathy card", // The worst thing to write in a sympathy card (Filipino/Tagalog)
  "पायलट ने उड़ान भरने से पहले जो सबसे बुरी बात कही: '______'", // The worst thing a pilot said before takeoff: '______' (Hindi)
  "Kötü bir süper kahraman ismi: ______",                // A bad superhero name: ______ (Turkish)
  "Pahin asia, jonka voi kuulla hammaslääkäriltä: '______'", // The worst thing to hear from your dentist: '______' (Finnish)
  "Nejhorší věc, kterou říct na prvním rande",            // The worst thing to say on a first date (Czech)
  "Det verste å rope under en begravelse",               // The worst thing to shout during a funeral (Norwegian)
  "ရေခဲမုန့်အရသာ အဆိုးဆုံးအမည်: ______",               // The worst ice cream flavor name: ______ (Burmese)
  "Perkara paling teruk untuk ditulis pada kad hari jadi", // The worst thing to write on a birthday card (Malay)
  "בדיחה שלעולם לא כדאי לספר בראיון עבודה",              // A joke you should never tell at a job interview (Hebrew)
  "Το χειρότερο πράγμα να πεις σε κηδεία: '______'",    // The worst thing to say at a funeral: '______' (Greek)
];

function cryptoRandInt(max: number): number {
  if (!Number.isInteger(max) || max <= 0) {
    throw new RangeError("max must be a positive integer");
  }

  // Rejection sampling avoids modulo bias when max does not divide 2^32.
  const limit = Math.floor(0x1_0000_0000 / max) * max;
  const array = new Uint32Array(1);
  while (true) {
    crypto.getRandomValues(array);
    if (array[0] < limit) {
      return array[0] % max;
    }
  }
}

function shuffle<T>(array: T[]): T[] {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = cryptoRandInt(i + 1);
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

const SOFT_DEDUPE_STOPWORDS = new Set([
  "a", "an", "the", "and", "or", "to", "of", "in", "on", "at", "for", "from",
  "with", "by", "into", "out", "up", "down", "over", "under", "after", "before",
  "during", "while", "when", "what", "why", "how", "that", "this", "these", "those",
  "is", "are", "was", "were", "be", "being", "been", "do", "does", "did", "just",
  "you", "your", "yours", "me", "my", "we", "our", "they", "their", "someone",
  "something", "somebody", "anyone", "anything", "person", "people",
  "worst", "best", "most", "least", "real", "really", "actual", "actually",
  "thing", "things", "way", "reason", "part", "line", "message", "name", "title",
  "say", "saying", "said", "hear", "hear", "find", "finding", "discover", "discovering",
  "would", "should", "could", "can", "never", "ever", "always", "again",
  "get", "gets", "got", "make", "makes", "made", "put", "write", "writes", "wrote",
  "bad", "terrible", "funny", "unhinged", "alarming", "suspicious", "concerning",
  "prompt", "prompts",
]);

function promptTokens(prompt: string): Set<string> {
  const normalized = prompt
    .toLowerCase()
    .replace(/_{2,}/g, " ")
    .replace(/['"!?.,:;()[\]{}\-–—/]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  const tokens = new Set<string>();
  for (const raw of normalized.split(" ")) {
    const token = raw.trim();
    if (!token) continue;
    if (token.length <= 2) continue;
    if (/^\d+$/.test(token)) continue;
    if (SOFT_DEDUPE_STOPWORDS.has(token)) continue;
    tokens.add(token);
  }
  return tokens;
}

function isSoftDuplicate(candidate: Set<string>, other: Set<string>): boolean {
  if (candidate.size === 0 || other.size === 0) return false;

  let intersection = 0;
  for (const t of candidate) {
    if (other.has(t)) intersection++;
  }

  if (intersection < 2) return false;

  const similarity = intersection / (candidate.size + other.size - intersection);
  return similarity >= 0.5 || (intersection >= 3 && similarity >= 0.34);
}

export function getRandomPrompts(
  count: number,
  exclude: Set<string> = new Set(),
): string[] {
  if (count <= 0) return [];

  const available = PROMPT_BANK.filter((p) => !exclude.has(p));
  const shuffled = shuffle(available);

  // Soft dedupe against already used prompts and already-selected prompts to
  // reduce "same vibe" repeats (same topic/frame, different wording).
  const recentTokenSets = Array.from(exclude, promptTokens);
  const selected: string[] = [];
  const selectedTokenSets: Set<string>[] = [];
  const deferred: string[] = [];

  for (const prompt of shuffled) {
    if (selected.length >= count) break;

    const tokens = promptTokens(prompt);
    const clashesWithRecent = recentTokenSets.some((t) => isSoftDuplicate(tokens, t));
    const clashesWithSelected = selectedTokenSets.some((t) => isSoftDuplicate(tokens, t));

    if (clashesWithRecent || clashesWithSelected) {
      deferred.push(prompt);
      continue;
    }

    selected.push(prompt);
    selectedTokenSets.push(tokens);
  }

  if (selected.length < count) {
    for (const prompt of deferred) {
      selected.push(prompt);
      if (selected.length >= count) break;
    }
  }

  return selected;
}
