export const MATCHSLOP_TOTAL_TURNS = 4;
export const MATCHSLOP_PROFILE_PROMPT_COUNT = 3;
export const MATCHSLOP_PERSONA_EXAMPLE_COUNT = 3;
export const MATCHSLOP_PLAYER_EXAMPLE_COUNT = 4;

export const MATCHSLOP_HUMAN_VOTE_WEIGHT = 2;
export const MATCHSLOP_AI_VOTE_WEIGHT = 1;
export const MATCHSLOP_POINTS_PER_WEIGHTED_VOTE = 25;
export const MATCHSLOP_WINNER_BONUS = 50;

export const MATCHSLOP_WRITING_SECONDS = 120;
export const MATCHSLOP_VOTING_SECONDS = 60;
export const MATCHSLOP_RESULTS_SECONDS = 20;

export const MATCHSLOP_PHOTO_PROMPT_ID = "__photo__";
export const MATCHSLOP_PHOTO_PROMPT_TEXT = "Their photo";
