import {
  MATCHSLOP_RESULTS_SECONDS,
  MATCHSLOP_TOTAL_TURNS,
  MATCHSLOP_VOTING_SECONDS,
  MATCHSLOP_WRITING_SECONDS,
} from "./config/game-config";

export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 8;
export const MAX_SPECTATORS = 0;
export const HOST_STALE_MS = 45_000;

export const DEFAULT_TOTAL_ROUNDS = MATCHSLOP_TOTAL_TURNS;
export const WRITING_SECONDS = MATCHSLOP_WRITING_SECONDS;
export const VOTING_SECONDS = MATCHSLOP_VOTING_SECONDS;
export const ROUND_RESULTS_SECONDS = MATCHSLOP_RESULTS_SECONDS;
