-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "aiCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "aiInputTokens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "aiOutputTokens" INTEGER NOT NULL DEFAULT 0;
