import type { QuizslopCategory } from "../types";

/**
 * A topic seed is an editorial prompt, not playable content. In particular, a
 * seed does not authorize AI generation until a separately reviewed evidence
 * bundle exists for it.
 */
export interface QuizSlopTopicSeed {
  id: string;
  label: string;
  /** The unnecessarily official title used by the standardized-test UI. */
  examTitle: string;
  category: QuizslopCategory;
  scope: string;
  comicAngle: string;
  safetyNotes: readonly string[];
  exclusions: readonly string[];
  /** Editorial replay-depth goal: 3 per tier = 12 reviewed questions per topic. */
  questionsPerTierTarget: 3;
  review: {
    approved: false;
    state: "DRAFT";
    reviewer: null;
    reviewedAt: null;
  };
}

type TopicSeedInput = Omit<QuizSlopTopicSeed, "questionsPerTierTarget" | "review">;

export const QUIZSLOP_SEED_QUESTIONS_PER_TIER_TARGET = 3 as const;

function draft(input: TopicSeedInput): QuizSlopTopicSeed {
  return {
    ...input,
    questionsPerTierTarget: QUIZSLOP_SEED_QUESTIONS_PER_TIER_TARGET,
    review: { approved: false, state: "DRAFT", reviewer: null, reviewedAt: null },
  };
}

const NO_SPECIAL_SAFETY_NOTES: readonly string[] = [];

/**
 * Unreviewed expansion backlog. These labels and scopes are intentionally
 * funny, but none of them are marked human-approved by code.
 */
export const QUIZSLOP_TOPIC_SEEDS: readonly QuizSlopTopicSeed[] = [
  draft({
    id: "cocktails",
    label: "Cocktails",
    examTitle: "Applied Ice & Tiny Umbrella Studies",
    category: "FOOD_DRINK",
    scope: "Classic recipes, ingredients, bar tools, glassware, and cocktail history.",
    comicAngle: "Treat every garnish like a legally binding architectural decision.",
    safetyNotes: ["Keep alcohol humor observational; never encourage dangerous consumption."],
    exclusions: ["drinking games", "personal consumption advice"],
  }),
  draft({
    id: "horology",
    label: "Horology",
    examTitle: "Advanced Knowing What Time It Is",
    category: "SCIENCE_NATURE",
    scope: "Mechanical watches, clocks, complications, timekeeping history, and terminology.",
    comicAngle: "Grant tiny gears the gravity normally reserved for constitutional crises.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["investment advice", "current auction prices"],
  }),
  draft({
    id: "cars",
    label: "Cars",
    examTitle: "Internal Combustion and External Validation",
    category: "OTHER",
    scope: "Automotive engineering, makes, models, motorsport history, and road-car design.",
    comicAngle: "Respect the machine while gently questioning the cup-holder strategy.",
    safetyNotes: ["Do not glamorize reckless driving."],
    exclusions: ["current resale values", "street-racing instructions"],
  }),
  draft({
    id: "cryptids",
    label: "Cryptids",
    examTitle: "Unverified Large Animal Administration",
    category: "ARTS_CULTURE",
    scope: "Cryptid folklore, reported sightings, cultural origins, and skeptical investigation.",
    comicAngle: "File Bigfoot sightings with the discipline of an expense report.",
    safetyNotes: ["Distinguish folklore and claims from established zoological fact."],
    exclusions: ["presenting hoaxes as fact", "harassing real communities"],
  }),
  draft({
    id: "marsupials",
    label: "Marsupials",
    examTitle: "Pouch-Based Logistics",
    category: "SCIENCE_NATURE",
    scope: "Marsupial biology, evolution, habitats, behavior, and species diversity.",
    comicAngle: "Treat the pouch as nature's most successful personal-item policy.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["pet-care advice"],
  }),
  draft({
    id: "reality-dating-shows",
    label: "Reality Dating Shows",
    examTitle: "Competitive Vulnerability on a Municipal Beach",
    category: "FILM_TV",
    scope: "Major formats, recurring conventions, production vocabulary, and show history.",
    comicAngle: "Analyze hot-tub diplomacy like a respected branch of political science.",
    safetyNotes: [
      "Roast formats and production conventions, not contestants' bodies or identities.",
    ],
    exclusions: ["current gossip", "private lives", "appearance-based jokes"],
  }),
  draft({
    id: "anime",
    label: "Anime",
    examTitle: "Animated Hair Physics and Narrative Escalation",
    category: "FILM_TV",
    scope: "Influential series and films, genres, studios, terminology, and production history.",
    comicAngle: "Give transformation sequences their deserved regulatory oversight.",
    safetyNotes: ["Treat fandom and Japanese culture respectfully."],
    exclusions: ["sexualized minors", "unreleased plot leaks"],
  }),
  draft({
    id: "young-adult-novels",
    label: "Young Adult Novels",
    examTitle: "Teenagers Correcting Entire Governments",
    category: "BOOKS_LANGUAGE",
    scope: "Major authors, series, genres, publishing history, and recurring literary conventions.",
    comicAngle: "Assume every standardized test may assign you a faction by lunch.",
    safetyNotes: ["Joke about tropes, not young readers."],
    exclusions: ["unpublished manuscripts", "sexual content involving minors"],
  }),
  draft({
    id: "hair-products",
    label: "Hair Products",
    examTitle: "Follicular Materials Science",
    category: "OTHER",
    scope: "Shampoos, conditioners, styling products, ingredients, formulation, and salon terms.",
    comicAngle: "Treat hold strength as if bridges depend on it.",
    safetyNotes: ["Do not demean hair textures, protective styles, or hair loss."],
    exclusions: ["personal dermatology advice", "appearance-based insults"],
  }),
  draft({
    id: "mma",
    label: "Mixed Martial Arts",
    examTitle: "Interdisciplinary Falling-Down Studies",
    category: "SPORTS",
    scope: "Rules, techniques, weight classes, organizations, and major moments in MMA history.",
    comicAngle: "Apply committee-meeting language to cage strategy.",
    safetyNotes: ["Do not celebrate brain injury or encourage unsupervised fighting."],
    exclusions: ["medical advice", "graphic injury descriptions", "current betting lines"],
  }),
  draft({
    id: "horse-racing",
    label: "Horse Racing",
    examTitle: "Equine Velocity Compliance",
    category: "SPORTS",
    scope: "Race formats, famous events, track terminology, breeding history, and rules.",
    comicAngle: "Treat hat size and furlong arithmetic as coequal sciences.",
    safetyNotes: ["Avoid gambling encouragement and jokes about animal injury."],
    exclusions: ["betting advice", "current odds", "graphic injuries"],
  }),
  draft({
    id: "cryptocurrencies",
    label: "Cryptocurrencies",
    examTitle: "Distributed Ledgers and Concentrated Regret",
    category: "INTERNET_TECH",
    scope: "Blockchain fundamentals, consensus, notable protocols, terminology, and history.",
    comicAngle: "Explain trustless systems with the solemnity of a group-chat treasurer.",
    safetyNotes: ["Educational facts only; never provide financial recommendations."],
    exclusions: ["price predictions", "investment advice", "token promotion"],
  }),
  draft({
    id: "machine-learning-llms",
    label: "Machine Learning & LLMs",
    examTitle: "Statistical Guessing at Industrial Scale",
    category: "INTERNET_TECH",
    scope: "Core ML concepts, model training, evaluation, neural networks, and LLM terminology.",
    comicAngle: "Make the model sit the exam it allegedly helped write.",
    safetyNotes: ["Avoid claims that models are conscious or infallible."],
    exclusions: ["vendor hype", "current benchmark rankings", "harmful implementation guidance"],
  }),
  draft({
    id: "math",
    label: "Mathematics",
    examTitle: "Numbers Filing Complaints About Letters",
    category: "SCIENCE_NATURE",
    scope: "Arithmetic, algebra, geometry, probability, famous results, and mathematical history.",
    comicAngle: "Treat a misplaced minus sign like an internal-affairs investigation.",
    safetyNotes: ["Never joke that struggling with math reflects intelligence."],
    exclusions: ["unsolved-problem speculation"],
  }),
  draft({
    id: "pharmaceuticals",
    label: "Pharmaceuticals",
    examTitle: "Tiny Tablets, Enormous Leaflets",
    category: "SCIENCE_NATURE",
    scope: "Drug discovery, dosage forms, pharmacology history, regulation, and terminology.",
    comicAngle: "Aim the jokes at packaging, nomenclature, and bureaucracy.",
    safetyNotes: ["Facts only; no diagnosis, dosing, drug-combination, or treatment advice."],
    exclusions: [
      "personal medical advice",
      "off-label recommendations",
      "controlled-drug instructions",
    ],
  }),
  draft({
    id: "home-audio-equipment",
    label: "Home Audio Equipment",
    examTitle: "Domestic Sound Reproduction and Neighbor Relations",
    category: "OTHER",
    scope: "Speakers, amplifiers, turntables, formats, acoustics, connectors, and hi-fi history.",
    comicAngle: "Respect the person who can hear a cable's emotional availability.",
    safetyNotes: ["Mention hearing safety when relevant; no unsafe electrical guidance."],
    exclusions: ["current buying advice", "unsafe wiring instructions"],
  }),
  draft({
    id: "deep-sea-fishing",
    label: "Deep-Sea Fishing",
    examTitle: "Pelagic Appointment Scheduling",
    category: "SPORTS",
    scope: "Target species, boats, gear, ocean zones, methods, conservation, and history.",
    comicAngle: "Treat a marlin like a client who has declined the calendar invite.",
    safetyNotes: ["Do not encourage illegal harvest or unsafe boating."],
    exclusions: ["live fishing reports", "poaching guidance", "graphic animal suffering"],
  }),
  draft({
    id: "deep-sea-oil-drilling",
    label: "Deep-Sea Oil Drilling",
    examTitle: "Extremely Offshore Office Work",
    category: "SCIENCE_NATURE",
    scope:
      "Platform types, subsea equipment, geology, engineering history, safety, and regulation.",
    comicAngle: "Present every valve as an employee with a terrifyingly specific job description.",
    safetyNotes: [
      "Treat disasters, deaths, and environmental damage factually, never as punchlines.",
    ],
    exclusions: [
      "operational sabotage",
      "disaster victims as jokes",
      "current proprietary procedures",
    ],
  }),
  draft({
    id: "deadly-australian-wildlife",
    label: "Deadly Australian Wildlife",
    examTitle: "Fauna-Based Risk Management: Australia",
    category: "SCIENCE_NATURE",
    scope: "Venomous and dangerous Australian species, biology, habitats, and evidence-based risk.",
    comicAngle: "Roast Australia's wildlife reputation without inflating the actual danger.",
    safetyNotes: ["Do not substitute trivia for emergency or wildlife-safety guidance."],
    exclusions: ["first-aid instructions", "animal cruelty", "fearmongering"],
  }),
  draft({
    id: "fermented-foods",
    label: "Fermented Foods",
    examTitle: "Microbial Lunch Supervision",
    category: "FOOD_DRINK",
    scope: "Fermentation organisms, methods, foods, regional traditions, and food science.",
    comicAngle: "Credit microbes as the unpaid interns of civilization.",
    safetyNotes: ["Do not provide risky home-fermentation or food-safety advice."],
    exclusions: ["medical claims", "unsafe preparation instructions"],
  }),
  draft({
    id: "chess",
    label: "Chess",
    examTitle: "Conflict Resolution on Sixty-Four Squares",
    category: "GAMES",
    scope: "Rules, tactics, openings, famous games, champions, and chess history.",
    comicAngle: "Describe one-square pawn movement with military-procurement urgency.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["live cheating assistance", "current tournament spoilers"],
  }),
  draft({
    id: "competitive-dog-grooming",
    label: "Competitive Dog Grooming",
    examTitle: "Advanced Poodle Topiary",
    category: "SPORTS",
    scope: "Competition classes, techniques, tools, judging, creative grooming, and history.",
    comicAngle: "Treat a sculpted bichon as the final presentation to the board.",
    safetyNotes: ["Roast the spectacle, never animal welfare or individual groomers."],
    exclusions: ["unsafe grooming instructions", "animal distress as humor"],
  }),
  draft({
    id: "elevators",
    label: "Elevators",
    examTitle: "Vertical Hallway Operations",
    category: "OTHER",
    scope: "Lift engineering, safety systems, control logic, etiquette, and history.",
    comicAngle: "Celebrate the machine that turned awkward silence into infrastructure.",
    safetyNotes: ["No bypass, entrapment, or unsafe repair guidance."],
    exclusions: ["repair instructions", "safety-system bypasses"],
  }),
  draft({
    id: "forklift-certification",
    label: "Forklift Certification",
    examTitle: "Pallet Mobility Licensure",
    category: "OTHER",
    scope: "Forklift types, stability, load handling, workplace rules, and training history.",
    comicAngle: "Give the load chart the gravitas of an ancient prophecy.",
    safetyNotes: ["Trivia never replaces accredited training or site-specific safety rules."],
    exclusions: ["operating instructions", "safety shortcuts", "certification impersonation"],
  }),
  draft({
    id: "container-shipping-port-logistics",
    label: "Container Shipping & Port Logistics",
    examTitle: "Very Large Boxes Going Somewhere Eventually",
    category: "OTHER",
    scope: "Containers, cranes, vessel classes, ports, trade routes, documentation, and logistics.",
    comicAngle: "Treat the bill of lading as maritime fan fiction with legal force.",
    safetyNotes: ["Avoid current security vulnerabilities and evasion tactics."],
    exclusions: ["smuggling methods", "live vessel security", "sanctions evasion"],
  }),
  draft({
    id: "vending-machines",
    label: "Vending Machines",
    examTitle: "Automated Snack Gatekeeping",
    category: "OTHER",
    scope: "Machine mechanisms, product history, unusual vending cultures, payment, and design.",
    comicAngle: "Frame a stuck granola bar as a constitutional crisis.",
    safetyNotes: ["Never encourage tipping, striking, or entering machines."],
    exclusions: ["tampering methods", "payment bypasses"],
  }),
  draft({
    id: "pigeons-war-sport",
    label: "Pigeons in War & Sport",
    examTitle: "Decorated Personnel With Extremely Small Feet",
    category: "HISTORY",
    scope: "Messenger pigeons, wartime service, pigeon racing, navigation, and notable birds.",
    comicAngle: "Give each pigeon the full dignity of a civil servant with wings.",
    safetyNotes: ["Treat wartime deaths factually and avoid animal-harm jokes."],
    exclusions: ["animal cruelty", "war casualties as punchlines"],
  }),
  draft({
    id: "bird-courtship-rituals",
    label: "Bird Courtship Rituals",
    examTitle: "Avian Romance Performance Review",
    category: "SCIENCE_NATURE",
    scope: "Displays, songs, nests, gifts, sexual selection, and species-specific behavior.",
    comicAngle: "Review elaborate dances as quarterly dating KPIs.",
    safetyNotes: ["Keep biological terminology accurate and non-explicit."],
    exclusions: ["graphic mating descriptions"],
  }),
  draft({
    id: "medieval-medicine",
    label: "Medieval Medicine",
    examTitle: "Clinical Leeches and Other Bold Initiatives",
    category: "HISTORY",
    scope:
      "Medical theories, practitioners, texts, remedies, institutions, and historical context.",
    comicAngle: "Aim at obsolete theories and institutional confidence, not sick people.",
    safetyNotes: ["Clearly frame historical treatments as history, not usable medical advice."],
    exclusions: ["treatment recommendations", "patients as punchlines", "graphic procedures"],
  }),
  draft({
    id: "conspiracy-theories-hoaxes",
    label: "Conspiracy Theories & Famous Hoaxes",
    examTitle: "Unsupported Claims Documentation",
    category: "ARTS_CULTURE",
    scope: "Origins, spread, evidence-based debunking, famous hoaxes, and media literacy.",
    comicAngle: "Roast bad evidence and corkboard methodology, never vulnerable believers.",
    safetyNotes: [
      "State false claims only in clear debunking context; never reinforce or operationalize them.",
    ],
    exclusions: [
      "presenting conspiracies as plausible",
      "hate-based conspiracies",
      "harassment targets",
    ],
  }),
  draft({
    id: "military-rations",
    label: "Military Rations",
    examTitle: "Shelf-Stable Morale Administration",
    category: "HISTORY",
    scope: "Ration types, preservation, menus, packaging, logistics, and military history.",
    comicAngle: "Evaluate crackers like defense-acquisition milestones.",
    safetyNotes: ["Do not make combat casualties, deprivation, or hunger the joke."],
    exclusions: ["victims as humor", "current operational logistics"],
  }),
  draft({
    id: "corporate-jargon-office-bureaucracy",
    label: "Corporate Jargon & Office Bureaucracy",
    examTitle: "Cross-Functional Synergy Compliance",
    category: "ARTS_CULTURE",
    scope:
      "Management vocabulary, office processes, org charts, meeting culture, and bureaucratic history.",
    comicAngle: "Use jargon until the sentence qualifies for its own steering committee.",
    safetyNotes: ["Roast systems and language, not workers or economic hardship."],
    exclusions: ["real-person workplace allegations"],
  }),
  draft({
    id: "taxidermy",
    label: "Taxidermy",
    examTitle: "Posthumous Posture Management",
    category: "ARTS_CULTURE",
    scope: "History, museum practice, tools, terminology, conservation, and notable specimens.",
    comicAngle: "Treat a museum fox's expression as a performance-management issue.",
    safetyNotes: ["Keep descriptions non-graphic and respect cultural or memorial contexts."],
    exclusions: ["graphic preparation instructions", "illegal wildlife trade"],
  }),
  draft({
    id: "distilled-spirits",
    label: "Liquor & Distilled Spirits",
    examTitle: "Beverage Distillation and Barrel Paperwork",
    category: "FOOD_DRINK",
    scope: "Distillation, spirit categories, ingredients, aging, regional traditions, and history.",
    comicAngle: "Treat barrel aging as an extremely slow team-building exercise.",
    safetyNotes: ["Keep alcohol humor observational; never encourage dangerous consumption."],
    exclusions: ["cocktail recipes", "drinking advice", "unsafe home distillation"],
  }),
  draft({
    id: "dictators-authoritarian-regimes",
    label: "Dictators & Authoritarian Regimes",
    examTitle: "Mandatory Leadership Studies",
    category: "HISTORY",
    scope:
      "Historical regimes, propaganda, institutions, resistance, succession, and democratic erosion.",
    comicAngle: "Aim satire upward at vanity, propaganda, and absurd institutions.",
    safetyNotes: [
      "Atrocities, victims, targeted groups, and political prisoners are never punchlines.",
    ],
    exclusions: [
      "atrocity trivia for laughs",
      "admiration",
      "victim-blaming",
      "current persuasion",
    ],
  }),
  draft({
    id: "high-end-furniture",
    label: "High-End Furniture",
    examTitle: "Executive Sitting Objects",
    category: "ARTS_CULTURE",
    scope: "Designers, movements, materials, iconic pieces, manufacturing, and furniture history.",
    comicAngle: "Ask why a chair needs a biography and then respectfully read it.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["current prices", "investment advice", "counterfeit authentication"],
  }),
  draft({
    id: "sleep-science",
    label: "Sleep Science",
    examTitle: "Unconsciousness Scheduling",
    category: "SCIENCE_NATURE",
    scope:
      "Sleep stages, circadian biology, research history, measurement, and general physiology.",
    comicAngle: "Treat bedtime as a recurring systems outage with pillows.",
    safetyNotes: ["General science only; no diagnosis or treatment advice."],
    exclusions: ["personal medical advice", "supplement advice", "sleep-disorder diagnosis"],
  }),
  draft({
    id: "ergonomics",
    label: "Ergonomics",
    examTitle: "Certified Chair Adjustment Studies",
    category: "SCIENCE_NATURE",
    scope:
      "Human factors, workplace design, measurement, research history, and general principles.",
    comicAngle: "Grant lumbar support the prestige of a cabinet position.",
    safetyNotes: ["General education only; no personal medical or workplace-compliance advice."],
    exclusions: ["injury diagnosis", "individual treatment", "legal compliance advice"],
  }),
  draft({
    id: "furry-culture",
    label: "Furry Culture",
    examTitle: "Anthropomorphic Arts & Convention Logistics",
    category: "ARTS_CULTURE",
    scope: "Fandom history, art, terminology, conventions, community, and creative practice.",
    comicAngle:
      "Celebrate the impressive project management required to invent a second wolf self.",
    safetyNotes: ["Be respectful, nonsexual, and precise; participants are never the punchline."],
    exclusions: ["sexual content", "dehumanizing jokes", "outing or identifying individuals"],
  }),
  draft({
    id: "germ-theory",
    label: "Germ Theory",
    examTitle: "Microscopic Accountability",
    category: "SCIENCE_NATURE",
    scope:
      "History of germ theory, foundational experiments, microbiology, sanitation, and terminology.",
    comicAngle: "Treat microbes as tiny defendants finally brought before science.",
    safetyNotes: ["Historical and scientific facts only; no diagnosis or treatment advice."],
    exclusions: ["medical advice", "pathogen cultivation", "misinformation"],
  }),
  draft({
    id: "office-supplies",
    label: "Office Supplies",
    examTitle: "Stationery Systems and Staple Deployment",
    category: "OTHER",
    scope: "Pens, paper formats, fasteners, filing, desk tools, inventions, and standards.",
    comicAngle: "Treat binder-clip load capacity as a matter of national preparedness.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["weaponizing office equipment"],
  }),
  draft({
    id: "municipal-parking-enforcement",
    label: "Municipal Parking Enforcement",
    examTitle: "Curbside Regulatory Theater",
    category: "OTHER",
    scope: "Parking signs, meters, curb rules, enforcement history, permits, and street design.",
    comicAngle: "Read a parking sign as the final boss of administrative literacy.",
    safetyNotes: ["Keep examples generic; do not provide ticket evasion or harassment tactics."],
    exclusions: ["evasion advice", "targeting enforcement workers", "current local legal advice"],
  }),
  draft({
    id: "airport-baggage-systems",
    label: "Airport Baggage Systems",
    examTitle: "Suitcase Routing Under Emotional Duress",
    category: "OTHER",
    scope: "Tags, conveyors, sorting, containers, tracking, security, and baggage-system history.",
    comicAngle: "Treat every carousel as a public performance of uncertain reunion.",
    safetyNotes: ["Do not expose current airport security weaknesses or bypass methods."],
    exclusions: ["security evasion", "live infrastructure vulnerabilities"],
  }),
  draft({
    id: "hvac",
    label: "HVAC",
    examTitle: "Indoor Weather Administration",
    category: "SCIENCE_NATURE",
    scope: "Heating, ventilation, air conditioning, refrigeration cycles, components, and history.",
    comicAngle: "Grant the thermostat the diplomatic status it already assumes it has.",
    safetyNotes: ["No electrical, refrigerant, combustion, or repair instructions."],
    exclusions: ["DIY repair guidance", "safety-system bypasses", "refrigerant handling"],
  }),
  draft({
    id: "water-treatment-plants",
    label: "Water-Treatment Plants",
    examTitle: "Municipal Beverage Preparation",
    category: "SCIENCE_NATURE",
    scope:
      "Treatment stages, filtration, disinfection, infrastructure, testing, and public-health history.",
    comicAngle: "Treat flocculation as the least marketable miracle in local government.",
    safetyNotes: ["No sabotage, contamination, or security-sensitive operational detail."],
    exclusions: ["system vulnerabilities", "contamination methods", "personal health advice"],
  }),
  draft({
    id: "theme-park-queue-engineering",
    label: "Theme-Park Queue Engineering",
    examTitle: "Applied Waiting With Decorative Rocks",
    category: "OTHER",
    scope: "Queue design, capacity, switchbacks, virtual queues, theming, and operations history.",
    comicAngle: "Measure how effectively fake barrels conceal forty-seven more minutes.",
    safetyNotes: ["Avoid actionable crowd-control weaknesses."],
    exclusions: ["security bypasses", "live evacuation plans"],
  }),
  draft({
    id: "luxury-mattresses",
    label: "Luxury Mattresses",
    examTitle: "Premium Horizontal Performance Surfaces",
    category: "OTHER",
    scope:
      "Materials, construction, support systems, mattress history, testing, and retail terminology.",
    comicAngle: "Ask why a rectangle has a brand story and a financing department.",
    safetyNotes: ["No medical, pain-treatment, or sleep-treatment claims."],
    exclusions: ["buying advice", "current prices", "medical recommendations"],
  }),
  draft({
    id: "concrete",
    label: "Concrete",
    examTitle: "Advanced Gray Substance Studies",
    category: "SCIENCE_NATURE",
    scope: "Cement chemistry, aggregates, reinforcement, curing, structures, and material history.",
    comicAngle: "Celebrate humanity's ability to make rocks with paperwork.",
    safetyNotes: ["Trivia is not structural, construction, or occupational-safety guidance."],
    exclusions: [
      "mix designs for real projects",
      "demolition advice",
      "structural recommendations",
    ],
  }),
  draft({
    id: "mascot-design",
    label: "Mascot Design",
    examTitle: "Institutional Creature Branding",
    category: "ARTS_CULTURE",
    scope: "Mascot history, costume design, visual identity, performance, and notable traditions.",
    comicAngle: "Audit whether a foam bird is sufficiently aligned with organizational values.",
    safetyNotes: ["Roast designs and institutions, not performers' bodies or identities."],
    exclusions: ["performer identification", "appearance-based insults"],
  }),
  draft({
    id: "ornamental-fish-competitions",
    label: "Ornamental Fish Competitions",
    examTitle: "Aquatic Pageant Compliance",
    category: "SPORTS",
    scope: "Show standards, fish varieties, judging, husbandry history, and competition culture.",
    comicAngle: "Give one exceptionally round goldfish the red-carpet treatment it has earned.",
    safetyNotes: ["Animal welfare is never a punchline; no risky husbandry advice."],
    exclusions: ["unsafe animal care", "animal distress as humor"],
  }),
  draft({
    id: "regional-potatoes",
    label: "Regional Potatoes",
    examTitle: "Comparative Tuber Geography",
    category: "FOOD_DRINK",
    scope: "Potato varieties, growing regions, culinary uses, agriculture, and cultural history.",
    comicAngle: "Treat starch percentage as a matter of regional honor.",
    safetyNotes: NO_SPECIAL_SAFETY_NOTES,
    exclusions: ["current commodity prices", "unsafe food preparation"],
  }),
  draft({
    id: "professional-wrestling",
    label: "Professional Wrestling",
    examTitle: "Narrative Athletics and Folding-Chair Governance",
    category: "SPORTS",
    scope: "Promotions, performers, match types, terminology, storytelling, and wrestling history.",
    comicAngle: "Analyze betrayal through the rigorous lens of entrance music.",
    safetyNotes: ["Do not encourage imitation of dangerous moves or joke about real injuries."],
    exclusions: ["move instructions", "real injuries as humor", "current private-life gossip"],
  }),
  draft({
    id: "competitive-spreadsheeting",
    label: "Competitive Spreadsheeting",
    examTitle: "Cell-Based Athletic Excellence",
    category: "GAMES",
    scope: "Spreadsheet esports, formulas, shortcuts, modeling tasks, event formats, and history.",
    comicAngle: "Announce a clean lookup formula like a last-second championship goal.",
    safetyNotes: ["Use fictional data; never include secrets, personal data, or dangerous macros."],
    exclusions: ["malicious macros", "real private datasets", "current event spoilers"],
  }),
] as const;

const TOPIC_SEEDS_BY_ID = new Map(QUIZSLOP_TOPIC_SEEDS.map((seed) => [seed.id, seed]));

export function getQuizSlopTopicSeed(id: string): QuizSlopTopicSeed | null {
  return TOPIC_SEEDS_BY_ID.get(id) ?? null;
}
